### ISSUE TITLE
EVENT: Event (Lager) massenhaft in unterschiedliche Gruppen im Produktivsystem kopieren

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#101]
Im Juni 2025 wird ein dreitägiger nationaler Grossanlass von Jungwacht Blauring für über 10‘000 Mitglieder stattfinden. Die jubla.db soll für diesen Grossanlass ebenfalls als innovatives Hilfsmittel eingesetzt werden können.

Als jublasurium möchten wir allen Teilnehmenden Scharen mit einer Lager-Anmeldung in der jubla.db unterstützten. Dazu soll in der **ersten Juliwoche 2024** allen teilnehmenden Scharen eine “Lageranmeldung” gemäss eigener, globalen Vorlage in ihre Schar-Ebene kopiert werden.

Support Ticket: https://help.puzzle.ch/#ticket/zoom/7711

Gewünschter Auftrag:

Wir liefern:
- Link/Hinweis zur "Vorlage" für ein Lager zum Beispiel so: https://**/groups/296/events/699
- Liste von allen Scharen (Typ Gruppe, ca. 260) welche eine Kopie erhalten sollen (zum Beispiel als Excel-Liste oder idealerweise so, wie ihr es am besten verwenden könnt, wir haben einen Event in dem sich Schar-Verantwortliche für ihre Schar angemeldet haben)

Wir hätten gern:
Alle Scharen (aus dieser Liste) soll in der ersten Juliwoche 2024 eine möglichst exakte Kopie dieser Vorlage in ihre Gruppe kopiert werden. Sie haben dann einen eigenen Event:Lager in ihrer Gruppe den sie dann unabhängig und selbständig weiterverwenden können.
Nach Möglichkeit gibt es einen Testlauf oder Abklärungen ob dynamische Verbindungen wie Beispielsweise ein Eingetragener Coach (event_coach) mitkopiert werden darf oder kann.

Absicht:
Der Grossanlass möchte sicherstellen, dass die Lageranmeldung nach ihren Bedürfnissen/Vorgaben durchgeführt wird. Zudem erleichtert eine Vorlage das (korrekte) erstellen einer Lageranmeldung für die Scharen massiv. 

**Optionen** 
(Weg zum Ziel bleibt gleich, Lösung muss einfacher oder im Sinne von Hitobito sein ohne signifikanten Wartungsaufwand/Mehrkosten zu generieren):
Wir sind bereit über Optionen oder Alternativen nachzudenken. Beispiel: Es gibt die Möglichkeit ein Lager zu Duplizieren. Dieses Feature kann auch direkt und unabhängig vom geöffneten Lager verwendet werden. (Link: /events/new?source_id=123, was wenn ein Duplizieren eines Event mit dem/einem access_token gehen würde? -> /new?source_id=123?shared_access_token=4567890 )
Oder ein Button, welcher das kopieren eines Lagers(Vorlage) ermöglicht?

Lagervorlage  | Status | Bemerkungen
-- | -- | --
Stage-Umgebung: https://jubla.puzzle.ch/groups/493/events/775  | ENTWURF | Bitte um Mitteilung (Gut zum Go), bevor getestet wird  |  
Live: https://db.jubla.ch/groups/9539/events/9643  | ENTWURF | Evtl. muss Lager neu erstellt werden, da Kontaktperson/Coach nicht angepasst werden kann: https://github.com/hitobito/hitobito/issues/2431  |  

Hier der Event mit dem sich Schar-Verantwortliche für ihre Schar angemeldet haben:
db.jubla.ch/groups/1/events/9222/participations 
- Die Spalte "Schar/originating_flock" wäre der Ort wohin die Vorlage kopiert werden soll.
- Das angemeldete Profil (Name Vorname) wäre idealerweise jeweils die "Kontaktperson/event_contact" der jeweiligen Lageranmeldung.

Nach Rücksprache vom 27.6 mit Puzzle geht der Release/Nacharbeiten vor, Arbeiten sind ab 3.7 möglich. Ab dem 4.7 wird eine genaue Terminierung erwartet.

**Comment by kronn** [comment]
Der Vorlage-Anlass 9643 ist gemäss den Anmeldungen im Anmeldeanlass 9222 kopiert worden.

**Comment by richardjubla** [comment]
**Interne Notizen zur Vorlage, ohne Bewertung**
(keine Relevanz für Puzzle)


- Kontaktperson ist hinterlegt 
- Anhang aus Vorlage wurde nicht übernommen
- Coach wurde aus Vorlage nicht übernommen
- In der Vorlage fehlte Ort und Bezeichnung
- https://www.jublasurium.ch/teilnahmebedingungen hat keinen Inhalt
- Externe Anmeldungen ist aktiviert (Folge: Adresse von Kontaktperson öffentlich einsehbar. Neue oder doppelte Profile möglich, Eltern erstellen Anmeldung/Profil ohne Elternzugang, Anmeldung ist aber direkt möglich)
- www.jublasurium.ch/essen führt zu einem Fehler E404
- Automatische Zuteilung ist nicht aktiv (siehe Bug https://github.com/hitobito/hitobito/issues/2706 )
- Feld Hausnummer Optional (Für J+S / NDS ist das Feld Hausnummer obligatorisch, beim ausfüllen muss das Feld mit einem Platzhalter für Strassen ohne Hausnummer befüllt werden)


Lageranmeldung:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/96797c74-367e-4d7a-8e2a-530bf9726d0b)
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/063a6879-604b-481b-82e5-905b7ff3f225)

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger 

**Soweit Danke!** Wir haben die Kopien geprüft und haben uns folgende Wünsche oder Gesprächsnotizen notiert:

- Anhang aus Vorlage einfügen wäre gewünscht (immer der gleiche, öffentlich für alle)
- Coach aus Vorlage (immer der gleiche. wäre recht wichtig da darüber die Administration/Exporte laufen)
- Aktivieren: Kontaktperson über neue Anmeldung per Mail benachrichtigen (optional, neu möglich da die Kontaktperson erfreulicherweise hiterlegt werden konnte)
- Feld Hausnummer obligatorisch setzten (Neu in Version 2.0.0, optional) 
- Log: Wo und welche Vorlagen wurden erstellt (Wenn es dies bereits gibt, wäre eine Liste mit allen Event-URLs interessant für eine nachträgliche Übersicht oder mögliche Anpassungen)

Bitte um Austausch und Gespräch, ob und was noch im Rahmen der Offerte machbar ist.

**Comment by richardjubla** [comment]
Vielen Dank für die Unterstützung. Von unserer Seite her erfolgreich umgesetzt!
