### ISSUE TITLE
NEJB: Projektstart - Administration und Projektsetup

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#109]
**User Story:**
Als PG Datenbank Ehemaligenwesen möchten wir ein eigenständiges Projekt für ein Feature in der jubla.db für das Ehemaligenwesen starten. Das Projekt folgt den bisherigen Bedingungen der jubla (Siehe Inkrements/Erwartungshaltungen). Aus administrativer Sicht soll es jedoch getrennt geführt werden (Offerte, Abrechnung, Dokumentation).

PG = Projektgruppe
NEJB = Netzwerk Ehemalige Jungwacht Blauring https://www.jubla.ch/ueber-die-jubla/ehemalige/netzwerk
Ehemalige: https://jubla.atlassian.net/wiki/x/MADeQg 
PG Datenbank Ehemaligenwesen = PG des NEJB 

**Aspekte:**
- Basierend auf der Besprechung vom 06.06.24 zwischen der PG Datenbank Ehemaligenwesen und Puzzle (Thomes Ellenberger) soll das eigenständige Projekt «Ehemalige» gestartet werden.
- Es ist möglich und sogar wahrscheinlich, dass neue Regelungen und Lösungen gefunden werden müssen für Funktionen der Datenbank wie zum Beispiel die Bestandsmeldung, Automatisationen, alumnus-Status etc. Für die Verfolgung dieser Themen braucht es eine Struktur/Gefäss. Puzzle übernimmt hier die aktive Projektleitung gemäss den Zielen der PG Datenbank Ehemaligenwesen. 
- Die Nachvollziehbarkeit muss auch für Nicht-ITler möglich sein. Daher ist eine umfassende Dokumentation von allen Arbeiten nötig. Über die Dauer des Projekts und die spätere Weiterentwicklung ist diese Dokumentation auf dem aktuellen Stand zu halten. 
- Mitglieder aber auch Vorstand im „Ehemaligenwesen“ sind auch Mitglied in Jungwacht Blauring Schweiz. Wir benötigen ein gemeinsames Verständnis und eine Grundlage um die Sichtbarkeit, Rollen und Berechtigungen inklusive Spezialfunktionen (Abo, Contact_Data, alumnus, etc.) im Einklang mit den Statuten/Datenschutzerklärung der Jubla/NEJB festlegen zu können.

**Definition of Done:**
- Das Projekt „Ehemalige“ mit eigenständiger Abrechnung angelegt.
- Die Nachvollziehbarkeit der Arbeiten (für NEJB/Jubla als Anwender/Tester ohne technisches Fachwissen) ist klar ersichtlicher Bestandteil aller Arbeiten sowie der Offerte.
- Anhand der erstellten Dokumentationen und Berichten kann das NEJB die Lösung nachvollziehen und abnehmen. 
- Die (technische) Dokumentation ist jeweils aktuell und kann für Weiterentwicklungen oder Konzepte beigezogen werden.
- Alle zukünftigen User Stories werden vor Übergabe an die PG Datenbank Ehemalige durch einen Entwickler von Puzzle getestet.

**Comment by ThomasEllenberger** [comment]
Issue geschlossen, da interner Task der Jubla. 
Kein Entwicklungsaufwand seitens Puzzle nötig.
