### ISSUE TITLE
Jublasurium Events für Anmeldungen sperren

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#136]
Als **Jublasurium** möchten wir allen Teilnehmenden Scharen mit einer Lager-Anmeldung in der jubla.db unterstützen. Aktuell findet die definitive Anmeldung für Teilnehmende, Leitende und Präsides via Jubla-Mitgliederdatenbank statt. 
Nun möchten wir auf ein von uns spontan gewähltes Datum zwischen 15.10 und 31.10.24 alle Jublasurium Lager gleichzeitig für neue Anmeldungen geschlossen werden. 

**Aspekte**

- Für das Jublasurium wurden Event (Lager) massenhaft in unterschiedliche Gruppen im Produktivsystem kopieret, Siehe #101 und #103 
- Es sollten keine neue Anmeldungen nach dem Zeitpunkt mehr möglich sein.
- Bearbeitung der bereits erfassten Anmeldungen weiterhin möglich (inkl. Event Details)
- Klären ob Anmeldeschluss genügt um weitere Anmeldungen zu sperren

**Definition of Done**

- Reaktionszeit auf Go von Jubla ist bekannt
- Alle Jublasurium Events (Lager) aus #101 und #103 sind am gewählten Datum für Anmeldungen geschlossen. (Keine neun Anmeldungen mehr möglich)
- Geklärt, ob Events auch "gesperrt" werden können. (Anmeldung öffnen ist nicht möglich)
 - Anmeldeschluss gemäss Kommunikaiton von Jubla ist gesetzt

**Comment by ThomasEllenberger** [comment]
>     * Klären ob Anmeldeschluss genügt um weitere Anmeldungen zu sperren

Stand heute gehen wir davon aus, dass man sich nach dem Anmeldeschluss nicht mehr an ein Event anmelden kann. Wir haben aktuell auch keinen Grund zu glauben, dass dies eine andere Funktionsweise hat.
Sollen wir hier Zeit investieren, dieses Verhalten zu verifizieren, oder gehen wir weiterhin davon aus, dass dies so funktioniert?

>     * Geklärt, ob Events auch "gesperrt" werden können. (Anmeldung öffnen ist nicht möglich)

Dies ist eine neue Anforderung für Hitobito. Hierfür gibt es meines Wissens heute keine Funktion. Sollen wir hier aktiv Zeit investieren, ein neues Feature für die Jubla zu entwickeln, damit Events gesperrt werden können, der genügt euch die Information dass dies nicht möglich ist?

**Comment by richardjubla** [comment]
@ThomasEllenberger 
> > ```
> > * Klären ob Anmeldeschluss genügt um weitere Anmeldungen zu sperren
> > ```
> 
> Stand heute gehen wir davon aus, dass man sich nach dem Anmeldeschluss nicht mehr an ein Event anmelden kann. Wir haben aktuell auch keinen Grund zu glauben, dass dies eine andere Funktionsweise hat. Sollen wir hier Zeit investieren, dieses Verhalten zu verifizieren, oder gehen wir weiterhin davon aus, dass dies so funktioniert?
> 

Wir gingen nicht davon aus, dass es nicht korrekt funktioniert, sondern fragten uns, ob es noch andere Möglichkeiten gibt, weitere Anmeldungen zu verhindern.

> > ```
> > * Geklärt, ob Events auch "gesperrt" werden können. (Anmeldung öffnen ist nicht möglich)
> > ```
> 
> Dies ist eine neue Anforderung für Hitobito. Hierfür gibt es meines Wissens heute keine Funktion. Sollen wir hier aktiv Zeit investieren, ein neues Feature für die Jubla zu entwickeln, damit Events gesperrt werden können, der genügt euch die Information dass dies nicht möglich ist?

Eine neue Anforderung scheint mir out-of-scope.  Ich sehe Konsens darin, dass die Rollen mit Schreibrechten (Lagerleitung etc.) und der Anmeldeschluss ausschlaggebend für den "Anmeldeschluss" sind.  Daraus ergibt sich wohl, dass über den Anmeldeschluss das Ziel erreicht wird: Bei allen Events den Anmeldeschluss (event_application_closing_at) auf den Vortag setzten.

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Freigabe für Umsetzung (asap)
Offizieller Anmeldeschluss: 30.10.2024

**Comment by ThomasEllenberger** [comment]
Umgesetzt durch Helpticket -> closed
