### ISSUE TITLE
BUG: Gruppen lassen sich nicht exportieren. (xlsx/csv)

### ISSUE THREAD

**Issue by tilloverflow** [hitobito/hitobito_jubla#137]
### Aktuelles Verhalten

Nach dem Anklicken von «Export» und dem Auswählen des gewünschten Dateiformates wird zwar die Benachrichtigung «Die Downloads werden vorbereitet, bitte warten.» angezeigt, jedoch wird die Adressliste nicht heruntergeladen. Auch nach 10 min. warten passiert nichts.

### Gewünschtes Verhalten

Nach dem Anklicken von «Export» und dem Auswählen des gewünschten Dateiformates wird die entsprechende Datei heruntergeladen.

### Schritte zu reproduzieren

1.	Beliebige Gruppe/Untergruppe auf Ebene Schar (Evtl. auch weiter betroffen?) öffnen
2.	Adressliste als xlsx/csv exportieren

### Wann ist der Fehler aufgetreten?

15.10.2024 19:00 UTC+2

### hitobito version

2.2.4

### Organisation

Jubla

**Comment by richardjubla** [comment]
@tilloverflow 

Danke für die Meldung! Wir konnten das Verhalten am 15.10.24 nachvollziehen. **Zum aktuellen Zeitpunkt funktioniert der Export.** Wir machen eine Meldung an Puzzle damit sie allfällige Prozesse/Verfügbarkeit des Features mitbekommen.

**Comment by richardjubla** [comment]
Getestet: In der Version 2.3.3 funktioniert der Export. Aus unserer Sicht kann das Ticket geschlossen werden.

**Comment by ThomasEllenberger** [comment]
Getestet. Funktioniert gemäss mir auch -> closed
