### ISSUE TITLE
Fehler beim Abo Versand

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_jubla#14]
Jubla meldet, sie Versände an die ch.praesides Email Adressen wären nicht vollständig verschickt worden. Unser MailLog meint, dass alle Emails verschickt wurden. 

```
[14] pry(main)> MailLog.where(mail_subject:  "Empfehlung: alle Jubla-Aktivitaeten bis 4. April streichen").where(mailing_list_name: 'ch.praesides')
=> [#<MailLog:0x00000000035437a8
  id: 14173,
  mail_from: "XX@XX.ch",
  mail_subject: "Empfehlung: alle Jubla-Aktivitaeten bis 4. April streichen",
  mail_hash: "ab99a223a87ac1c0ad8b7ebdcf8311cf",
  status: "completed",
  mailing_list_name: "ch.praesides",
  mailing_list_id: 41,
  created_at: Fri, 13 Mar 2020 21:51:29 CET +01:00,
  updated_at: Fri, 13 Mar 2020 21:54:16 CET +01:00>,
 #<MailLog:0x0000000003543640
  id: 14207,
  mail_from: "XX.XX@XX.ch",
  mail_subject: "Empfehlung: alle Jubla-Aktivitaeten bis 4. April streichen",
  mail_hash: "3e3a57c92ed9bb9e559ba7fc14899132",
  status: "completed",
  mailing_list_name: "ch.praesides",
  mailing_list_id: 41,
  created_at: Sat, 14 Mar 2020 15:33:08 CET +01:00,
  updated_at: Sat, 14 Mar 2020 15:35:53 CET +01:00>]
```

Allerdings wurde eine MailingListe nicht richtig aufgelöst

```
MailLog.find(14133)
=> #<MailLog:0x000000000321a630
 id: 14133,
 mail_from: "XX.XX@XX.ch",
 mail_subject: "Empfehlung: alle Jubla-Aktivitaeten bis 4. April streichen",
 mail_hash: "20e701e705af10e57b2adf30f554e2d8",
 status: "unkown_recipient",
 mailing_list_name: "[#<Mail::Field 0x5675520 ",
 mailing_list_id: nil,
 created_at: Fri, 13 Mar 2020 19:22:50 CET +01:00,
 updated_at: Fri, 13 Mar 2020 19:22:50 CET +01:00>

```

**Comment by psunix** [comment]
das Fehlerhafte Mail ist leider nicht mehr in der Inbox bzw. im failing Folder vorhanden.
eine Analyse ist so schwierig.

aus irgend einem Grund konnte die Mailingliste nicht aus den Headers extrahiert werden. 

assignment des Mailinglistenname erfolgt hier: https://github.com/hitobito/hitobito/blob/master/app/domain/mail_relay/base.rb#L251

bei Jubla Prod gibt es immerhin 150 MailLog Einträge mit mailing_list_name: "[#<Mail::Field 0x4907870 "

Letzter Record ist vom 3. Juli 2020 (17842)

**Comment by amaierhofer** [comment]
Ich kann mir vorstellen, dass das daran lag, das früher eventuell 2 oder mehr Einträge im Header waren, wir das aber nicht richtig berücksichtig haben. Ich denke spätestens mit hitobito/hitobito@18ece375de9716fa4825b698c94f81f1ff7b7e78 sollte das behoben sein
