### ISSUE TITLE
KONFIG: Bemerkungen bei Anlässen, Kursen und Lager löschen (13 Mt.)

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#141]
Als FG Datenbank möchten wir Scharen und Event-Veranstalter entlasten, dass sie nicht notwendige oder nicht legitimierbare Daten unbeschränkt aufbewahren. Dazu sollen die Antworten zu Events nach 13 Monaten automatisch gelöscht werden, damit dies der Vorstand oder die Event-Administration nicht manuell machen muss.

Wir beziehen uns auf https://github.com/hitobito/hitobito_jubla/pull/120, https://github.com/hitobito/hitobito_sac_cas/issues/367 und https://github.com/hitobito/hitobito_sac_cas/issues/367

Vorgabe:

Mit dem Release werden die bestehenden Werte auf 13 Monate gesenkt und im Verband über die jubla.db (Release/Handbuch) kommuniziert. Die Scharen hatten Zeit, allfällige Archiv-Wünsche oder spezielle Anforderungen abzudecken.

Vorgeschlagene Werte:

```
Settings.event.participations.delete_additional_information_after_months = 13
Setting.sevent.participations.delete_answers_after_months = 13
```

**Comment by richardjubla** [comment]
Der Aufwand ist vermutlich minimal. Bitte wie vorschlagen ohne Offerte (Auf Supportkosten umsetzten).

**Comment by TheWalkingLeek** [comment]
Erledigt in https://github.com/hitobito/hitobito_jubla/commit/49f5a9a075450367d798d12d2e8d703d2065a286

**Comment by richardjubla** [comment]
Stichproben auf Produktivem System: OK und auf Prod abgenommen.
