### ISSUE TITLE
ROLLE: Kind anpassen

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#146]
Als nationale Geschäftsstelle möchte ich die Rolle Kind an unsere Vorgaben anpassen.

**Aspekte:**

- Alle Berechtigungen für die Rolle Kind entfernen. Die Rolle soll nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen. Begründung: Verwalter*innen dürfen keine andere Kinder sehen können, wenn sie ihre Rechte über das Kind ausweiten. Kinder benötigen keine Situationen im Jubla-Alltag um andere Kinder sehen.

Vorschlag für die bisherige Rolle "Kind"

```
* Bund
* Kanton
* Region
* Schar
  * Schar
  * Kindergruppe
    * Kind: []
```

**Definition of Done**

Die Rolle Kind hat keine Berechtigungen mehr. (Kinder und deren Verwalter*innen sollen andere Kinder nicht sehen können)

**Comment by richardjubla** [comment]
Auf Stage erfolgreich getestet.  Wohl umgesetzt mit https://github.com/hitobito/hitobito_jubla/pull/152

**Comment by ThomasEllenberger** [comment]
> Auf Stage erfolgreich getestet. Wohl umgesetzt mit #152

Korrekt

**Comment by richardjubla** [comment]
Rolle auf Prod. korrekt geprüft.
