### ISSUE TITLE
Person ohne Rollen verschwindet

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#154]
Wird einem Profil alle Rollen entfernt, landet es nicht in der Gruppe "ohne Rollen", sondern befindet sich dann in keiner bestimmten Gruppe. Und das Profil kann dann nicht wieder bearbeitet werden wie z.b. Rollen hinzugefügt werden.

Das Profil verbleibt ohne Zugehörigkeit in der Datenbank. 

Beispiel: Samuel Blum https://jubla.puzzle.ch/groups/507/people/1628

![Image](https://github.com/user-attachments/assets/824395b7-fafc-41a5-86dd-99f3c1c5f7ca)

Auffällig ist zudem, dass das Profil dann nicht mehr bearbeitet werden kann, es fehlt ein Bearbeitungs-Buttons (siehe Bild). Ist das working as intended bei Profilen ohne Rollen?

**Comment by richardjubla** [comment]
Eventuell ein Duplikat oder es finden sich ergänzende Informationen hier: https://github.com/hitobito/hitobito_jubla/issues/53

**Comment by kronn** [comment]
Die Person ist nicht verschwunden, sie ist nur in einer anderen Gruppe unter "ohne Rollen" aufgeführt: http://hitobito.local:3000/groups/508/deleted_people (Sieht man natürlich nur mit passenden Rechten). Genauso kann man der Person weiterhin Rollen zuweisen.

Das "nicht mehr bearbeiten können" von Profilen ohne Rollen ist tatsächlich "working as intended". Wenn jemand keine Rolle mehr hat, besteht auch kein Grund zum Bearbeiten. Entweder wird die Person gelöscht oder sie im System bis sie wieder gebraucht wird, dann bekommt sie eine neue Rolle. Wenn sie aktiv verwendet wird, hat sie vermutlich ohnehin besser eine Rolle wie "Extern" oder "Kontakt" und kann dann bearbeitet werden.

Wie lange eine Person ohne Rollen im System bleiben darf ist nicht technisch geregelt, da es stark von der Organisation und deren Regeln abhängt.

**Comment by richardjubla** [comment]
> Die Person ist nicht verschwunden, sie ist nur in einer anderen Gruppe unter "ohne Rollen" aufgeführt: http://hitobito.local:3000/groups/508/deleted_people (Sieht man natürlich nur mit passenden Rechten). Genauso kann man der Person weiterhin Rollen zuweisen.
> 
> Das "nicht mehr bearbeiten können" von Profilen ohne Rollen ist tatsächlich "working as intended". Wenn jemand keine Rolle mehr hat, besteht auch kein Grund zum Bearbeiten. Entweder wird die Person gelöscht oder sie im System bis sie wieder gebraucht wird, dann bekommt sie eine neue Rolle. Wenn sie aktiv verwendet wird, hat sie vermutlich ohnehin besser eine Rolle wie "Extern" oder "Kontakt" und kann dann bearbeitet werden.
> 
> Wie lange eine Person ohne Rollen im System bleiben darf ist nicht technisch geregelt, da es stark von der Organisation und deren Regeln abhängt.

Gemäss unserem Verständnis soll ein Profil immer in der Gruppe in ohne Rollen landen, in dem es als letztes eine Rolle hatte. Es gibt oder soll keine andere Gruppe geben. Wie ist hier das verhalten?

**Comment by kronn** [comment]
Die Person ist in der Ansicht "Ohnen Rollen" der Ebene, aus der die Person entfernt wurde. Die Person wurde aus Gruppe 508 entfernt, was zufällig auch eine Ebene ist.

Der genannte Link zeigt die Person im Kontext der absoluten Root-Gruppe (507). Die passiert, wenn man eine Person ohne Rollen über die Suche findet und entweder im Suchergebnis oder im Quicksearch auswählt. 

Es gibt durchaus Möglichkeiten, das anders zu machen, aber das wäre dann ein komplett neues (vermutlich auch sinnvolles) Feature. Im Rahmen dieses Bugreports stelle ich aber nur fest, dass die Person nicht verschwunden ist, da sie über die Suche auffindbar ist. Weiterhin kann ihr eine Rolle gegeben werden. In der Ebene, in der sie zuletzt war, wird sie auch konkret unter "ohne Rollen" aufgeführt.

**Comment by richardjubla** [comment]
@kronn 

Mir sind folgende Aspekte wichtig:

- Profile ohne Rollen gehören immer in die Gruppe "ohne Rollen" in der jeweilig letzten Gruppe/Ebene. Voraussetzung ist, dass es keine Profile geben soll welche nicht mehr durch den jeweilig verantwortlichen Verein (Gruppe/Ebene) verwaltet werden kann. Profile ohne jegliche Zuordnung soll und darf es nicht geben da sonnst "niemand" für sie zuständig ist (Security, Administration, Datenschutz, etc.).
-  Ich bin mir nicht sicher, ob der in diesem Ticket erwähnte Fall das Problem korrekt darstellt. In https://github.com/hitobito/hitobito_jubla/issues/53 haben wir Fälle von Profilen "ohne Rollen" versucht aufzuzeigen.
- Vielleicht hat uns (zusätzlich) verwirrt, dass die aktive Rolle "Ehemalig" nicht im Profil angezeigt wird

**Comment by richardjubla** [comment]
Meeting 12.12.24 - Auf Stage-Umgebung zum testen bereit.

**Comment by patriziajubla** [comment]
habe das soeben mit folgendem Profil durchgespielt und es landete bei keiner Ebene in der Gruppe ohne Rolle. Sondern im "Nirvana". 

![image](https://github.com/user-attachments/assets/871057a9-52d9-4101-aec9-98c97a1cf0dd)

**Comment by patriziajubla** [comment]
Testing:
Profil vor entfernen der Rolle:
![image](https://github.com/user-attachments/assets/92902409-82ef-4b24-93d4-b9f29ba9cc34)
Profil nach entfernen der Rolle:
![image](https://github.com/user-attachments/assets/46e2b8e8-a1fe-4edc-8c0f-63487f707c16)
Gruppe ohne Rollen:
![image](https://github.com/user-attachments/assets/a76ee539-72f5-444b-a660-448116ef1b02)


Funktioniert meines Erachtens.

**Comment by tobiasstern** [comment]
@kronn Es mir mehrfach passiert, dass ich von einer Person eine Leitungsrolle entferne und die Person dann im System verschwindet, scheinbar ohne Rolle und Gruppe.

Getestet mit https://jubla.puzzle.ch/groups/507/people/1583
Er war Scharleitung hier https://jubla.puzzle.ch/groups/41/people

Versuch selber mal in der Gruppe z.b. dem Berger Oli die Rolle zu entfernen und schau, ob du es reproduzieren kannst.

**Comment by richardjubla** [comment]
> Die genannte Person ist unter https://jubla.puzzle.ch/groups/41/deleted_people#person_1583 gelistet. Ich kann dieser Person wieder Rollen zuweisen oder sie endgültig löschen, wenn die Daten nicht mehr benötigt werden. Es funktioniert also.

Nein, gemäss meiner Erkentniss die [DoD von S2](https://github.com/hitobito/hitobito_jubla/issues/121) ist nicht erreicht: Ein Profil ohne Rolle kann aus der Gruppe entfernt werden. Ein Vorstand (Rolle Leitung) muss in der Lage sein, Profile in seiner Ebene (Verein) aus allen Rollen zu entfernen und das Profil löschen können (sofern das Technisch gemäss Dokumentation vorgesehen ist). Siehe auch https://github.com/hitobito/hitobito_jubla/issues/108





> Der Zustand "scheinbar ohne Rolle und Gruppe" beruht darauf, dass die Person im falschen Kontext angezeigt wird. Das sie ohne Rolle ist, ist in der Tat so. Die scheinbare Gruppenlosigkeit liegt daran, dass keine aktive Rolle mehr vorhanden ist. Diese Ansicht kann über mehrere Wege erreicht werden. Das kann natürlich alles angepasst werden. Dies wäre aber ein neues Feature, welches erstmal spezifiziert werden sollte.

Das Feature oder das korrekte vorgehen ist in S2 beschrieben. Was ist den aktuell der Ablauf und wie haben wir es in S2 definiert? Gleich oder abweichend?


> Da die Person über die Hauptsuche und die Suche bei der Rollenvergabe gefunden wird, ist sie nicht verschwunden. Da sie weiterhin in der richtigen Gruppen "ohne Rollen" aufgelistet wird, hat die hier verantwortliche Person die Möglichkeit, über Datenlöschung oder erneute Rollenvergabe zu entscheiden. Insgesamt sehe ich hier keinen Bug.

Doch, für den Vorstand "verschwindet" die Person und sie kann sie nicht mehr finden. Der Vorstand ist aber weiterhin für die Person zuständig. Wenn das Profil in eine neue Ebene rutscht ist dann einen neue Zuständigkeit nötig oder eine Zugrifsanfrage oder ähnliches. 


> 
> Wenn die Person ohne Rollen in der Hauptsuche "nicht gefunden" wird, fehlen dem Suchenden die Rechte, die Person im Kontext der obersten (vermutlich ohnehin falschen) Gruppe anzuzeigen. Wer aber auf die Pseudogruppe "ohne Rollen" Zugriff hat, sieht dort die Person.

Wir verstehen es aktuell so, dass nicht die Rollen falsch sind, sondern der Ort wo das Profil landet. Wäre das Profil in der korrekten Gruppe/Ebene, würde die verantwortliche Person das Profil korrekt finden. Die Zugriffe auf die Pseudogruppe "ohne Rollen" gilt doch pro Ebene/Gruppe? Dann müssten doch die Profile auch entsprechend korrekt darin landen?
