### ISSUE TITLE
NEJB: Error 500 bei Abos in Subgruppe Passivmitglieder

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#158]
Fehlermeldung und Abo erfolgreich erstellt  

 ![Image](https://github.com/user-attachments/assets/bbb5865a-eed5-4bac-9387-5721327af5f8)

Wenn ich das Abo anschaue 
![Image](https://github.com/user-attachments/assets/8c4ff18f-8577-4fe5-ada1-bcb87e2fff3e)

Bei klick auf den Abonamen 
![Image](https://github.com/user-attachments/assets/0fdeb236-c0d1-4b2c-b8ad-f3cd3ff88ca2)

 
NEJB Passsivmitglieder 
Ähnliches verhalten beim Erstellen eines Abos [Passivmitglieder](https://jubla.puzzle.ch/groups/514/mailing_lists/49/messages) 
(Fehlermeldung) in der Gruppe NEJB Passsivmitglieder. Jedoch kann ich dort auf den Abonamen klicke und erhalte folgende Darstellung. 
![Image](https://github.com/user-attachments/assets/c895258d-498e-4a39-80cc-e83f97e01c56)

 

> Letzte und diese Woche gab es Probleme mit dieser "500er" meldung. Bitte nochmals testen coh @Nicole 
 
Neue Test von 14.11. mit dem gleichen Problem
![Image](https://github.com/user-attachments/assets/65074ad6-618d-4fbe-a119-6b4590308042)

**Comment by richardjubla** [comment]
Meeting 12.12.24 - Auf Stage-Umgebung zum testen bereit.

**Comment by patriziajubla** [comment]
abo erstellt, bearbeitet und Abonnenten hinzugefügt ohne Fehlermeldung gestestet.
