### ISSUE TITLE
NEJB - S5: Untergruppen Ebene Schar "Ehemalige" umbenennen in "Ausgetretene Leitungspersonen"

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#160]
Gemäss #124 sind die Untergruppen der Ebene Schar "Ehemalige" umzubenennen in "Ausgetretene Leitungspersonen"

**Comment by kronn** [comment]
`SELECT MAX(name) AS name, parent_id, count(*) AS anzahl FROM groups WHERE name = 'Ehemalige' AND type = 'Group::FlockAlumnusGroup' AND deleted_at IS NULL GROUP BY parent_id ORDER BY count(*) DESC, parent_id ASC LIMIT 10`

**Comment by tobiasstern** [comment]
@kronn Wurde das deployed? Ich sehe überall die Gruppe "Ehemalige" und keine umbenannten?

<img width="317" alt="Image" src="https://github.com/user-attachments/assets/f0737def-9f46-42d3-962e-afe26f841f03" />
https://jubla.puzzle.ch/groups/460

**Comment by kronn** [comment]
Der Rake-Task wurde tatsächlich noch nicht ausgeführt. Das ist jetzt erledigt:

```
-- Consolidating duplicated Ehemalige-groups
   -> Consolidated 3 groups into Group#615: Ehemalige
   -> Consolidated 2 groups into Group#616: Ehemalige
   -> 1.0349s
 
-- Renaming Alumnus-groups on flock-level
   -> 0.0151s
   -> 73 rows
