### ISSUE TITLE
NEJB - S5: Rolle Ehemalig umbenennen in Austritt

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#161]
Gemäss #125 soll die Rolle «Ehemalig({BisherigeRolle})» umbenannt werden in «Austritt({BisherigeRolle})»

**Comment by patriziajubla** [comment]
![image](https://github.com/user-attachments/assets/79d97674-a23e-4287-9658-095b6ebca048)
Frage: muss es hier auch unbenannt werden?:
![image](https://github.com/user-attachments/assets/33691a45-216e-4735-b06a-5cc4933b79d2)

**Comment by tobiasstern** [comment]
hey @kronn, ging das vergessen?

**Comment by kronn** [comment]
> hey @kronn, ging das vergessen?

Ja. Kann anpassen. Zu was soll es denn geändert werden? Austrittsrollen? @richardjubla @patriziajubla

**Comment by richardjubla** [comment]
> @marcowilla
> 
> Text für den Platzhalter "Ehemalige Rollen" festlegen. Vorschlag: Austrittsrollen, so belassen oder Austritte (so wie im Filter)

@kronn 

"Ehemalige Rollen" in `Austritte` umbenennen. 
(Kontext: Der Platzhalter zeigte ehemaligen Rollen welche in Austritt oder im Filter "Austritte" gezeigt werden. Der Asside orientiert sich daran.)
