### ISSUE TITLE
NEJB - S7: Cleanup Mitglied-Rolle in Ehemalige

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#168]
Siehe #162 :

> - Auf Ebene Schar: Der bisherige automatisierte Prozess mit dem Entfernen der Rolle und Vergabe von neuen Rollen soll nicht verändert werden!
> - Auf allen anderen Ebenen(Kanton/Region/Bund) wird der Prozess angepasst: Beim entfernen der letzten Rolle vergibt das System dem Profil die Rolle «Austritt({BisherigeRolle})» und nicht mehr die Rolle "Mitglied" (der Gruppe "Ehemalige")

Als Folge von Punkt 2 soll das bestehende System aufgeräumt werden:
Für diese Ebenen: Den Personen, welche bereits im System in dieser Rolle/Gruppe sind, soll die Rolle "Mitglied" in der automatisch erstellten Gruppe "Ehemalige" entfernt werden. Manuelle Ehemalige-Gruppen explizit ausgeschlossen!

**Comment by kronn** [comment]
Manueller Merge, wodurch die Github-Automatismen nicht greifen...
