### ISSUE TITLE
Berechtigung 

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_jubla#17]
Die Jubla möchte gerne auch die Funktion Impersonation nutzen. Bitte folgender Rolle die Berechtigung 'impersonation' geben:
Bund -> Bundesleitung -> Mitglied

Ist: Mitglied: [:admin, :layer_and_below_full, :contact_data]
Soll: Mitglied: [:admin, :layer_and_below_full, :contact_data, :impersonation]

**Comment by amaierhofer** [comment]
Wie mit Anna besprochen habe ich die `IT Support` Rolle auf der Bundesebene hinzugefügt. Diese Rolle hat nur die Berchtigung zu impersionieren, d.h. die Personen die impersioniert werden können sind immer abhängig von den anderen Rollen die diese Person bereits hat. Damit ist besser erkennbar wer die Berechtigung zum impersionieren hat.

**Comment by olibrian** [comment]
Berechtigung wurde im letzten Release am 2020-10-06 auf die Prod Umgebung gebracht. Rolle kann nun vergeben werden.
