### ISSUE TITLE
NEJB: Vorausgefüllter "Kurzname" im Formular beheben

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#170]
Im Formular wird das Feld "Kurzname" vom Browser immer automatisch vorausgefüllt. Wenn unbemerkt wird es so gespeichert und führt zu Fehlern.

Das Feld soll von Browsern nicht mehr automatisch ausgefüllt werden

**Comment by richardjubla** [comment]
Meeting 12.12.24 - Auf Stage-Umgebung zum testen bereit.

**Comment by patriziajubla** [comment]
neuer Ehemaligenverein erstellt, Kurzname wurde nicht ausgefüllt.

**Comment by richardjubla** [comment]
> neuer Ehemaligenverein erstellt, Kurzname wurde nicht ausgefüllt.

Die Felder werden je nach Browser/Autocomplete ausgefüllt. Ich sehe das beschriebene Verhalten nach wie vor: https://github.com/hitobito/hitobito/issues/2581

**Comment by tobiasstern** [comment]
> > neuer Ehemaligenverein erstellt, Kurzname wurde nicht ausgefüllt.
> 
> Die Felder werden je nach Browser/Autocomplete ausgefüllt. Ich sehe das beschriebene Verhalten nach wie vor: [hitobito/hitobito#2581](https://github.com/hitobito/hitobito/issues/2581)

Hallo Richi
Es ist bekannt, dass dies immer wieder vorkommen kann. Wir hatten besprochen, dass im Rahmen dieses Tickets der akute Fall für "Kurzname" behoben wird. Eine vollständige Behebung im gesamten System würde die Devs zu viel Zeit kosten, vor allem die Suche nach den verschiedenen Stellen.

Wenn solche "Problem-Felder" entdeckt werden, kann ein Dev diese mit minimalem Aufwand beheben. Ich schlage vor, dass entdeckte Felder in dem Ticket https://github.com/hitobito/hitobito/issues/2581 als Kommentar hinzugefügt/gesammelt werden.
