### ISSUE TITLE
NEJB: Administratoren sind sichtbar für Kontaktdatenberechtigte

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_jubla#175]
Vgl. Bild
![Image](https://github.com/user-attachments/assets/51f69c91-fea2-4b24-862f-c316b5c2865f)

Wenn man eine Rolle hat, die :contact_data hat, kann diese auch die Administratoren auf der obersten Ebene sehen.

- [x] Reproduzieren
- [ ] Dokumentieren
- [ ] Anpassungsmöglichkeiten vorschlagen

**Comment by richardjubla** [comment]
Meeting 12.12.24 - Auf Stage-Umgebung zum testen bereit.

**Comment by richardjubla** [comment]
Ja, das gezeigte Verhalten ist korrekt. Die Aussagen von Matthias korrekt.
