### ISSUE TITLE
Kursbestimmungen für externe Anmeldungen anzeigen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_jubla#22]
Anfrage von der Jubla:

Und zwar ist uns gerade aufgefallen, dass externe TN wenn sie sich bei uns für einen Kurs anmelden wollen die Kursbestimmungen nicht sehen:

https://db.jubla.ch/groups/1/public_events/6086 (Du darfst nicht eingeloggt sein bei der jubla.db, sonst siehst du sie natürlich)

Ich hab das rasch durchgespielt und mich als externe Person z.B einer Pfaderin angemeldet. Erst wenn ich angemeldet bin erscheinen die Kursbestimmungen auf der jubla.db und dann auch im PDF welches generiert wird (siehe Anhang).

Das macht aus unserer Sicht aber überhaupt keinen Sinn, da es wichtig ist dass sie die Kursbestimmungen vor der Anmeldung kennen.

Kannst du dem bitte nachgehen und mit der FG Datenbank oder puzzle klären wo der Fehler ist.

Für uns wäre wichtig, wenn dies so schnell wie möglich angepasst wird. Die Kurse fürs 2021 sind bereits wieder offen und die Anmeldung trudeln ein.

**Comment by carlobeltrame** [comment]
@kronn der PR #23 ist noch nicht gemerged..?

**Comment by kronn** [comment]
Sorry, da bin ich durcheinander gekommen. Danke fürs wieder eröffnen, das issue schließt sich ja automatisch wenn der PR fertig ist.
