### ISSUE TITLE
GROUPS: Fehler beim Fusionieren von Gruppen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_jubla#31]
## Aktuelles Verhalten

Teilweise können zwei Gruppen nicht fusioniert werden. HTTP Error Code 422, 500

## Gewünschtes Verhalten

Beliebige Gruppen können fusioniert werden. 

## Schritte zum reproduzieren

1. Auf dem Info-Tab einer Gruppe unter Bearbeiten die Option Fusionieren wählen
2. Name für die neue Gruppe sowie die Gruppe mit welcher fusioniert werden soll auswählen
3. "Gruppe fusionieren" wählen

# Tech-Spec

- Sentry error 1: Gültigkeitsprüfung ist fehlgeschlagen: PLZ ist nicht gültig
  - https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47907/?query=is%3Aunresolved
- Sentry error 2: Gültigkeitsprüfung ist fehlgeschlagen: Person muss ausgefüllt werden
  - https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47320/?query=is%3Aunresolved%20merge
- Sentry error 3: NoMethodError: undefined method `type' for nil:NilClass
  - https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47766/?query=is%3Aunresolved%20merge

**Comment by mtnstar** [comment]
es gibt eine Rolle an der keine Peson assigned ist: Role.id 355481

**Comment by richardjubla** [comment]
Error 422 bedeutet Validation Fehler. 
Für den User: Datenbank kann deine Fusion nicht durchführen, da gewisse Daten fehlen oder nicht korrekt vorhanden sind.


Wir validieren Gruppen auf folgende Aspekte:
Name: Muss vorhanden sein
E-Mail: Format einer Mailadresse, Domain muss erreichbar sein (DNS-Eintrag)
Beschreibung: Maximallänge: 2^16 - 1 (= 65535) Zeichen
Adresse: Maximallänge: 1024 Zeichen
Kontaktperson: Muss in der Gruppe sein
Land: Muss im Dropdown vorhanden sein
PLZ: Muss eine Schweizer PLZ sein


Anhand dieser Aspekte können wir prüfen oder klären, ob der Fehler eher in den Daten oder in der Technik zu vermuten ist.
