### ISSUE TITLE
PERSON: Label "Anmeldungen"

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#45]
(Input/Konzept)

Es geht um den Begriff "Anmeldungen" im Profil -> Tab "Info". (people_controller_spec.rb)

Hier erscheinen Kurse, bei denen zum Beispiel die Bestätigung noch offen ist oder Vorbedingungen fehlen. Es handelt sich also um einen Prozess welcher mit Begriffen wie applications, Bewerbungen, Voranmeldung oder eben Anmeldungen umschreiben werden kann. Sobald die Bedingungen erfüllt sind, "rutscht" der Kurs in die Tabelle "Meine nächsten Anlässe".

Wir möchten klarer ersichtlich machen, dass noch etwas passieren muss, bevor die Anmeldung eben wirklich eine definitive Kursanmeldung ist. Vielen User*innen scheint nicht bewusst zu sein, dass noch etwas passieren muss, bevor ihr Anmeldung "definitiv" ist.

**Vorschläge/Gedanken**
- Umbenennung des Titels  "Anmeldungen" in "Offene Kursanmeldung(en)" oder "Offene Anmeldungen"
- Hilfstext-Feld zur Liste "Anmeldungen"
- Anzeigen der Bedingungen wie Vorbedingung oder Kursfreigabe in dieser Liste (ähnlich wie im Tab "Anmeldungen" bei Kursen) 

![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/7ad63174-3eee-4623-8b52-5d028122649f)

![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/6540e7a2-c2b3-48e7-89eb-94e85d9db522)

**Comment by nchiapol** [comment]
Wir hatten uns auch an dem Begriff gestört und das auf Voranmeldung geändert. Das hatte aber leider ein paar unerwünschte Nebenwirkungen, da die gleiche Übersetzung an diversen Anderen Stellen auch verwendet wird, wo Anmeldung korrekt ist: https://github.com/hitobito/hitobito_cevi/pull/96

**Comment by richardjubla** [comment]
Konzept wird geschlossen. Die Nebenwirkungen sind bekannt.
