### ISSUE TITLE
KURSE: Sammlung bekannter Bugs im Kurswesen der JublaDB

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jubla#47]
## Ziel dieses Tickets:
Aufgrund von Anpassungen im Kurswesen vermutlich durch https://github.com/hitobito/hitobito_cevi/issues/79, https://github.com/hitobito/hitobito_cevi/issues/80 funktioniert bei der Jubla das Kurswesen aktuell nicht mehr zufriedenstellend.
Langfristig wollen wir mit den Jugendvereinen anschauen, ob eine Vereinheitlichung des Anlass-, Kurs- und Lagerwesens möglich ist. 
Ziel dieses Tickets ist jedoch nur, die Bugs im aktuellen Kurswesen der Jubla soweit zu fixen dass ein Release der JublaDB möglich ist. 
Dieses zweiteilige Vorgehen wurde bereits in https://github.com/hitobito/hitobito/issues/2122 diskutiert.

## Usecases Jubla 
Samlung der Usecases der Jubla, welche mindestens funktionieren müssen dami ein Release stattfinden kann.
- Kurs ohne Warteliste 
- Kurs mit Warteliste
- Kurs mit "Freigabe"
- Kurs mit "Priorisierung"

## Kritische Bugs welche vor einem Release behoben werden müssen
- [ ] 
- [ ] 
- [ ] 

## Weitere bekannte Bugs
- [ ] https://github.com/hitobito/hitobito/issues/2120
- [ ] 
- [ ]

**Comment by ThomasEllenberger** [comment]
Ich habe drei Useacases durchgetestet um zu verstehen, wie diese aktuell auf der Testumgebung funktoinieren.
@richardjubla Kannst du bestätigen, wie diese Usecases bei euch verwendet werden, und ob diese auf eurer Produktivumgebung gleich funktionieren, oder wie diese aktuell auf eurer Testumgebung funktionieren?

## Standarteinstellungen:
Standartmässig sind auf der Jubla Integration die folgenden Optionen an-/Abgewählt:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/c82b4649-0510-428e-9968-b45a935aee22)
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/ac30b00f-7424-4a3f-86f1-12501ae8d5b6)

## Kurs ohne Warteliste:
1.1.0: Eine Person meldet sich an einen Kurs ohne Warteliste anwelcher noch nicht voll ist, und erhält die folgende Bestätigung:
 ![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/0a08c8be-4e13-4e23-8cf5-e446ac55f056)
1.1.1: Sie erhält ausserdem ein Email zugeschickt welche die Anmeldung bestätigt:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/e28c2e9f-9c07-45bf-a876-cb1f4ce730f5)
1.1.2: Die Person wird auf dem Kurs automatisch als Teilnehmerin hinzugefügt und erscheint bei den Zugeteilten Teilnehmenden.
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/0a8aa023-8584-42e7-af25-9d92313690c1)


1.2.0: Eine Person meldet sich an einem Kurs ohne Warteliste an und der Kurs ist voll. Sie erhält die folgende Nachricht:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/0d19c9f7-9273-4db4-a23a-08738c8c1626)
1.2.1: Die Person erhält eine Email welche sagt, dass dies nur eine Voranmeldung ist, welche noch nicht definitiv ist und noch bestätigt werden muss: 
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/f93fc3aa-f9a7-4410-98e8-ee4a71bdddc0)
1.2.2: Die Person erscheint bei den Anmeldungen vom Kurs, ist aber nicht auf der nationalen Warteliste.
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/01cd5af3-a01c-4358-95ba-d7a5b66455fc)
1.2.3: Auch bei Kursen ohne Warteliste können die Anmeldungen welche auf Wartelisten sind angezeigt werden:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/7f071436-a2aa-4c58-9cf3-d6a3e6e59dd9)
1.2.4 Auch bei Kursen ohne Warteliste können angemeldete Personen zur nationalen Warteliste zugeteilt werden:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/12bd9383-763a-4ed0-b818-0d0840f2d439)


## Kurs mit Warteliste:
2.1.0: Eine Person meldet sich an einen Kurs mit Warteliste an und der Kurs ist noch nicht voll. Sie erhält die folgende Nachricht:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/7084816c-f085-453d-8ba8-f431d387e244)
2.1.1: Sie erhält ausserdem ein Email zugeschickt welche die Anmeldung bestätigt:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/bf0486d0-b2ed-4358-9887-8982f26fdebb)


2.2.1: Eine Person meldet sich an einen Kurs mit Warteliste an und der Kurs ist bereits voll belegt. Sie erhält die folgende Nachricht:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/3447005b-d6b0-4553-8289-e35760169fe0)
2.2.2: Die Person erhält eine Email welche sagt, dass dies nur eine Voranmeldung ist, welche noch nicht definitiv ist und noch bestätigt werden muss:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/5e931714-ad68-4fb1-a4c2-997a58541ab8)
2.2.3: Person erscheint in den Anmeldungen des Kurses und ist auf der nationalen Warteliste:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/f345a8ff-528b-4ca5-9497-4ff0542405b6)


## Kurs mit Freigabe:
3.1.0: Feature funktioniert aktuell nicht wie gewünscht. Siehe https://github.com/hitobito/hitobito/issues/2120

## Kurs mit Priorisierung:
4.1.0: Ist der Checkmark für Priorisierung auf einem Kurs aktiv, erscheint bei der Anmeldung zusätzlich die Option weitere Kurse als Priorität 2 und 3 anzugeben:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/12d0470d-a1e6-42a6-a888-83e06446a2b5)
4.1.1: Eine Person meldet sich bei einem Kurs mit Priorisierung an und es hat noch Platz im Kurs. Sie erhält die folgende Meldung:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/e4e92e6f-adb9-4c7e-9b94-b52db6738710)
4.1.2: Auf ihrem Profil sieht sie die Anmeldepriorität: 
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/552ea6db-0ecc-4688-ae55-98fee372938e)
4.1.3 Die Person ist automatisch als Prio 2 und 3 zu den ausgewählten Kursen angemeldet. 
4.1.4: Die Person erscheint auf dem Kurs unter den Anmeldungen. Die option Warteliste greift unabhänig von der Einstellung Priorisierung. Allerdings landet man erst automatisch auf der Warteliste, wenn deim Kurs auch schon die maximale Anzahl Teilnemende zugeordnet sind, nicht erst angemeldet:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/10513601-68c3-4fd1-9d8e-a799c2b7df65)
4.1.5: Sind alle Plätze belegt und ist die Warteliste ebenfalls eingeschaltet erhält die Teilnehmerin die folgende Fehlermeldung:
![grafik](https://github.com/hitobito/hitobito_jubla/assets/100761305/08a7e529-325e-48be-9548-e6042899a057)

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger 

Ich konnte deine Uscases mit der Kursadministration besprechen und wir haben folgende Antworten:


> `**Grundsätzliches**:
> 
> Bei einem Kurs (nicht Anlass) soll grundsätzlich nie eine Person, die sich angemeldet hat, direkt zu "zugeteilte Teilnehmende" rutschen. Denn es müssen immer Aufnahmebedingungen überprüft werden (auch solche, die sich technisch nicht überprüfen lassen, z.Bsp., ob diese Person als Expert*in in der kommenden Kurssaison eingeplant ist. Dies wird als Frage via Anmeldeangaben abgefragt und danach mit der Zustellung des unterzeichneten PDF geprüft.)
> Wir sehen ähnliche oder die gleichen Fehler/Rückmeldungen, wie vom Cevi bereits in #168 (Test Kursanmeldungen) gemeldet wurden.
> 
>  
> 
>  
> 
> **Kurs ohne Warteliste**
> 
> **Grundsätzliches**
> 
> Wird nicht wie beschrieben angewendet.
> Funktioniert anders auf produktiver db, weil Funktion "Verwendet Warteliste" vorhanden ist
> 
>  
> 
> 1.1.0
> 
> Angemeldete Person sollte nicht direkt in "zugeteilte Teilnehmende" rutschen, auch wenn es noch freie Plätze hat. Da zuerst alle Aufnahmebedingungen von der Kursadministration des Organisators überprüft werden müssen.
> Textvorschlag, der nach der provisorischen Anmeldung auf der db angezeigt werden soll: "Es wurde eine Voranmeldung für die Teilnahme von VORNAME NAME in KURSNAME erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden."
> 
> 1.1.1
> 
> Vorschlag für E-Mail-Text (kann selbst durch Jubla angepasst werden):
> 
>  
> 
> Anlass: E-Mail Voranmeldung
> 
>  
> 
> Betreff: Voranmeldung eingegangen
> 
> Inhalt:
> 
> Hallo {recipient-name}
> 
>  
> 
> Wir haben deine Voranmeldung für die Teilnahme an folgendem Anlass erhalten:
> 
>  
> 
> {event-details}
> 
>  
> 
> Deine Anmeldung ist noch nicht definitiv und muss erst noch vom Kursorganisator geprüft und bestätigt werden.
> 
>  
> 
> Falls du ein Login hast, kannst du deine Anmeldung unter folgender Adresse einsehen:
> 
>  
> 
> {application-url}
> 
>  
> 
> WICHTIG: Bitte beachte, dass du die Bestätigung je nach Anlass unterschrieben an die unter «Info» erwähnte Kontaktadresse senden musst.
> 
>  
> 
> 1.1.2
> 
> Die Person sollte automatisch zu den "Anmeldungen" hinzugefügt werden, nicht "zugeteilte Teilnehmende".
> 
>  
> 
> 1.2.0
> 
> Sollte usus sein, wenn sich eine Person für einen Kurs anmeldet, egal ob er voll ist oder noch freie Plätze hat.
> 
>  
> 
> 1.2.1
> 
> Mailtext-Vorschlag siehe 1.1.1
> 
>  
> 
> 1.2.2
> 
> Sollte usus sein, wenn sich eine Person für einen Kurs anmeldet, egal ob er voll ist oder noch freie Plätze hat.
> 
>  
> 
> 1.2.3
> 
> Zur Kenntnis genommen. Kein Kommentar von pew, weil nicht im Arbeitsalltag verwenden.
> 
>  
> 
> 1.2.4
> 
> Zur Kenntnis genommen. Kein Kommentar von pew, weil nicht im Arbeitsalltag verwenden.
> 
>  
> 
> -> 1.1.0+1.1.1+1.1.2 wollen wir gesammelt mit einem Häklein steuern können, damit eine angemeldete Person zwingend unter "Anmeldungen" landet und keine direkte Anmeldung möglich ist. Diese Funktion sollen pro Kurs aktiviert oder deaktiviert werden können. Grundeinstellung: (Warteliste) aktiv
> 
> -> Ab 1.2.0 bis und mit 1.2.2 funktioniert nicht auf Test-db. Person rutscht direkt in "zugeteilte Teilnehmende" obwohl die maximale Teilnehmendenzahl erreicht ist. ->
> 
> -> Angezeigte Ziffer von Anmeldungen in der Kursübersicht entspricht nicht der Realität.
> 
>  
> 
> **Kurs mit Warteliste**
> 
> **Grundsätzliches**
> 
> Die nationale Warteliste wird von unserem Verband praktisch nicht verwendet.
> Pew hat keine Erfahrungswerte diesbezüglich.
> Technische Begriffe fehlen, nicht nachvollziehbar für rib+pew
> Jubla verwendet nationale Warteliste sehr selten. Auch wenn wir mit der nationalen Warteliste arbeiten würden, möchten wir, dass alle Personen unabhängig von Vorbedingungen (max. TN-Zahl, Freigabe, Anerkennungen, etc.), die sich anmelden, in der rechten Spalte/"Anmeldungen" landen.
> 2.1.0 - 2.2.3 würde ziemlich sicher aufgrund von Anpassungen bei "Kurs ohne Warteliste 1.2.0 - 1.2.2" ebenfalls gültig werden, was die Jubla begrüsst.
> 
>  
> 
> 2.1.0
> 
> Angemeldete Person sollte nicht direkt in "zugeteilte Teilnehmende" rutschen, auch wenn es noch freie Plätze hat. Da zuerst alle Aufnahmebedingungen von der Kursadministration des Organisators überprüft werden müssen.
> Textvorschlag, der nach der provisorischen Anmeldung auf der db angezeigt werden soll: "Es wurde eine Voranmeldung für die Teilnahme von VORNAME NAME in KURSNAME erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden." / "Es sind derzeit alle Plätze belegt, die Anmeldung ist auf der Warteliste."
> 
>  
> 
> 2.1.1
> 
> Vorschlag für E-Mail-Text (kann selbst durch Jubla angepasst werden):
> 
>  
> 
> Anlass: E-Mail Voranmeldung
> 
>  
> 
> Betreff: Voranmeldung eingegangen
> 
> Inhalt:
> 
> Hallo {recipient-name}
> 
>  
> 
> Wir haben deine Voranmeldung für die Teilnahme an folgendem Anlass erhalten:
> 
>  
> 
> {event-details}
> 
>  
> 
> Deine Anmeldung ist noch nicht definitiv und muss erst noch vom Kursorganisator geprüft und bestätigt werden.
> 
>  
> 
> Falls du ein Login hast, kannst du deine Anmeldung unter folgender Adresse einsehen:
> 
>  
> 
> {application-url}
> 
>  
> 
> WICHTIG: Bitte beachte, dass du die Bestätigung je nach Anlass unterschrieben an die unter «Info» erwähnte Kontaktadresse senden musst.
> 
>  
> 
> 2.2.1
> 
> Sollte usus sein, wenn sich eine Person für einen Kurs anmeldet, egal ob er voll ist oder noch freie Plätze hat.
> Ich gehe davon aus, dass das Verhalten so ok ist, wenn mit der Warteliste gearbeitet werden möchte. (pew verwendet nicht und keine Erfahrungswerte)
> 
>  
> 
> 2.2.2
> 
> Mailtext-Vorschlag siehe 2.1.1
> 
>  
> 
> 2.2.3
> 
> Sollte usus sein, wenn sich eine Person für einen Kurs anmeldet, egal ob er voll ist oder noch freie Plätze hat.
> Ich gehe davon aus, dass das Verhalten so ok ist, wenn mit der Warteliste gearbeitet werden möchte. (pew verwendet nicht und keine Erfahrungswerte)
> 
>  
> 
>  
> 
> Kurs mit Freigabe
> 
> 3.1.0 korrekt, bitte Bug lösen (Issue hitobito2120)
> 
>  
> 
>  
> 
> **Kurs mit Priorisierung**
> 
> **Grundsätzliches**
> 
> Die Priorisierungsfunktion wird von unserem Verband praktisch nicht verwendet.
> 
>  
> 
> 4.1.0
> 
> Welche Kurse werden als zusätzliche Auswahl angezeigt? Jene derselben Kursart, die man als 1. Prio angegeben hat oder jene vom "eigenen" Jubla-Kanton?
> 
> -> Ideal wäre, wenn Kurse derselben Kursart angezeigt werden.
> 
>  
> 
> 4.1.1
> 
> Angemeldete Person sollte nicht direkt in "zugeteilte Teilnehmende" rutschen, auch wenn es noch freie Plätze hat. Da zuerst alle Aufnahmebedingungen von der Kursadministration des Organisators überprüft werden müssen.
> Textvorschlag, der nach der provisorischen Anmeldung auf der db angezeigt werden soll: "Es wurde eine Voranmeldung für die Teilnahme von VORNAME NAME in KURSNAME erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden."
> 
>  
> 
> 4.1.2
> 
> Zur Kenntnis genommen. Geprüft, keine Fehler gefunden.
> 
>  
> 
> 4.1.3
> 
> Zur Kenntnis genommen. Geprüft, keine Fehler gefunden.
> 
>  
> 
> 4.1.4
> 
> Zur Kenntnis genommen. Geprüft, keine Fehler gefunden.
> Angemeldete Person sollte nicht direkt in "zugeteilte Teilnehmende" rutschen, auch wenn es noch freie Plätze hat. Da zuerst alle Aufnahmebedingungen von der Kursadministration des Organisators überprüft werden müssen.
> Textvorschlag, der nach der provisorischen Anmeldung auf der db angezeigt werden soll: "Es wurde eine Voranmeldung für die Teilnahme von VORNAME NAME in KURSNAME erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden."
> 
>  
> 
> 4.1.5
> 
> Textvorschlag, der nach der provisorischen Anmeldung auf der db angezeigt werden soll: "Es wurde eine Voranmeldung für die Teilnahme von VORNAME NAME in KURSNAME erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden." / "Es sind derzeit alle Plätze belegt, die Anmeldung ist auf der Warteliste."
> 
>  
> 
> **Fazit/Wunsch Jubla-Kursadmin**
> 
> Neue Anmeldungen rutschen immer nur in "Anmeldungen". Nicht "zugeteilte  Teilnehmende". Egal, ob der Kurs mit/ohne Warteliste, mit/ohne Priorisierung erfasst wurde, egal max. TN-Zahl.
> Textvorschlag Anzeige auf jubla.db gemäss 1.1.0
> Mailvorschlag gemäss 1.1.1 (kann selbst durch Jubla angepasst werden)
> Kursadministration des Kursorganisators prüft Anmeldung. Sofern alle Aufnahmebedingungen erfüllt, verschiebt Kursadministration die angemeldete Person zu "zugeteilte Teilnehmende".
> Angemeldete Person sieht auf jubla.db folgenden Text in grün "Du bist für diesen Anlass angemeldet."
> Angemeldete Person erhält folgendes E-Mail (kann selbst durch Jubla angepasst werden):
> 
>  
> 
> Anlass: E-Mail Anmeldebestätigung
> 
>  
> 
> Betreff: Bestätigung der Anmeldung
> 
> Inhalt:
> 
> Hallo {recipient-name}
> 
>  
> 
> Du hast dich für folgenden Anlass angemeldet und deine Anmeldung wurde bestätigt:
> 
>  
> 
> {event-details}
> 
>  
> 
> Unter folgendem Link kannst du deine Anmeldung einsehen:
> 
> {application-url}
> 
>  
> 
> Hinweis: Das Dokument im Anhang dient nur zu deiner Information.
> 
>  
> 
> Liebe Grüsse
> 
> Jungwacht Blauring
> 
>  
> 
> ------------------------------------------
> 
> Dies ist eine automatisch generierte Nachricht, bitte antworte nicht darauf. Bei Fragen zum Anlass wende dich an die angegebene Kontaktperson.`
>

**Comment by richardjubla** [comment]
**Notizen zur Kursanmeldung mit Option **Priorisierung****
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/3b8cbd0c-dd25-45ac-80f9-5ae29e978143)


- Die möglichen Ausweichdaten sind teilweise nicht möglich oder nicht "hilfreich", da sie auch in der Vergangenheit (mehrere Jahre) liegen können. (Ist aber wohl nicht ein "Bug", da die Information über vorhandene Kurse wichtiger ist als die direkte Möglichkeit zur Anmeldung?)
- Event (E-Mail) - Voranmeldung eingegangen: Erfolgt eine Voranmeldung, muss diese von der Adressverwaltung (gemäss Text) oder der Scharleitung (gemäss Technik) freigegeben werden. Das E-Mail mit der Voranmeldung geht ausschliesslich an das Profil welches sich angemeldet hat. Die Aufforderung und Information zur "Freigabe" muss zwingend und explizit über einen anderen Weg (mündlich, Briefpost, etc.) erfolgen. Aus meiner Sicht ein sehr negativer Faktor für eine einfache Anmeldung.
- Die Scharleitung muss das Profil mit der Anmeldung in seiner Gruppe/Ebene finden, es aufrufen und darüber bis zum Kurs navigieren. Hier kann sie die Anmeldung Freigeben oder Ablehnen. (Workaround: Angemeldete Person wird aufgefodertert, das Erhaltene E-Mail an die Scharleitung zu senden. Der darin enthaltene Link zum Kurs kann die Scharleitung direkt zur Freigabe verwenden)
- Es ist mir nicht bekannt welche Auswirkung/Ablauf der Kursadministration für die Aktionen  "Anmeldung löschen" "Abmelden" oder  "Ablehnen" haben. Insbesondere auf die weiteren Anmeldungen mit Prio 2 oder Prio 3 
- Die Option "Provisorische Anmeldungen: Gruppenleiter/-innen können Personen provisorisch anmelden" scheint nicht zu funktionieren. Ein Scharleiter im gleichen Kanton wie der ausgeschriebene Kurs konnte keine provisorischen Anmeldungen machen. Nur die Kursadministration kann "Einladungen" machen. Dies ist aber eine andere Funktion!
- Einladungen sind durch die Kursadministration möglich. Wie beschrieben, wird hier keine E-Mail ausgelöst und muss ebenfalls  (mündlich, Briefpost, etc.) erfolgen.

**Comment by richardjubla** [comment]
Dieses Ticket kann geschlossen werden:

- Zum aktuellen Zeitpunkt sind keine Anpassungen vorgesehen (Kursadmin befasst sich zuerst einmal mit der Situation auf dem produktiven System)
- Die minimalen Anforderungen aus https://github.com/hitobito/hitobito_jubla/issues/58 werden bei Bedarf für das Jahr 2024 neu in Betracht gezogen
- Neue Entwicklungen beim Thema Kursverwaltung soll nach Möglichkeit einbezogen werden. Wir beteiligen uns an angebotenen Gesprächen.
