### ISSUE TITLE
Nextcloud-Verbindung auf Ebene 

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#52]
**User-Story**

Als Schar (Ebene/Gruppe) möchte ich meinen Mitgliedern und Ehrenamtlichen kollaborativ nutzbaren Speicherplatz und Dokumentablage/Dokumentbearbeitung mit einer eigenen Nextcloud-Instanz ermöglichen. Sie kann die Nextcloud-Instanz in der jubla.db Eintragen und damit können sich alle in der Gruppe verwalteten Menschen (Mitglieder) direkt in Nextcloud anmelden und haben dort die jeweils gültigen Berechtigungen (Rollen) aus der jubla.db.

https://github.com/hitobito/hitobito/issues/1854

**Aspekte**

- Die jubla.db (Hitobito) ermöglicht die Einbindung (Verknüpfung) der Open Source Software Nextcloud auf Basis einer einzelnen Schar (Ebene/Gruppe).

Wir suchen bestehende Lösungen, die für die Jubla-Welt anpassbar und zugänglich sind. Das heisst, wir setzen auf Lösungen, die auch von Personen, die sich zukünftig in der Jubla engagieren möchten, weiterentwickelt werden können, insbesondere gut dokumentierte Open-Source-Software.

Nextcloud ist eine freie Software für das Speichern von Daten (z. B. Dateien, Kalender, Kontakte etc.) auf einem Server. Auf die Daten kann der Anwender sowohl über eine Weboberfläche als auch mit Client-Applikationen (Smartphone und Desktop) zugreifen. Server und Clients können sich dabei synchronisieren. Nextcloud ermöglicht dem Anwender dadurch, auf einen zentralen und konsistenten Datenbestand von vielen Endgeräten aus zuzugreifen und diesen mit anderen Anwendern optional zu teilen. Neben der Datenhaltung bietet Nextcloud Funktionalitäten für Videokonferenzen und verschiedene Office-Applikationen über die Weboberfläche.Über Nextcloud und ausgewählte Add-Ons wäre Kollaboration (OnlyOffice) bis hin zu Projektmanagement (OpenProject) über den kompletten Verein möglich. 

Integration: Die jubla.db und Nextclound können zusammen kombiniert werden. Hitobito setzt mit einem Partner dieses Projekt aktuell um. Gemäss Interpretation/Wissensstand soltle dies ein stark gewünschtes Bedürfnis der Scharen und KaLeis abdecken.

Kosten: Je nach Auslegung ist Nextcloud “die einzige Lösung”, um ein kompetitives Angebot zur Konkurrenz der Cloud-Anbieter (Microsoft/Google/etc.) entgegenzuhalten.

Chance/Innovation: Die Erweiterung der Datenbank um Kollaborations-Services und Cloud-Speicher ist ein  Bedürfnis und wäre ein logische Innovation auch entsprechend der Vision der Datenbank. Die Datenbank könnte hier mit einem Angebot einen signifikanten Beitrag zur Digitalisierung und Stärkung der Scharen leisten.

Risiken: In direkter Konkurrenz zu Cloud-Anbietern bergen die Support/Wartungskosten, eingeschränkter Leistungsumfang oder Schulungsaufwand das Risiko für gescheiterte Projekte. Es darf keine strategische Verbindung, Zwang oder Abhängigkeit zwischen der Datenbank und einer Nextcloud Instanz entstehen. 

**Definition of Done**

- Die Verbindung zwischen jubla.db und Nextcloud wird von der FG Datenbank weiterverfolgt (Ebene Schar)
- FG Datenbank kennt die wichtigsten Faktoren (Technik, Kosten, Abhängigkeiten)
- FG Datenbank kann evtl. bereits Implementierung testen
- Dokumentation: Schritt-für-Schritt Anleitung für Scharen (inkl. Hinweise für Nextcloud) / Erfolgt durch jubla/FG DB

**Comment by richardjubla** [comment]
Die @jubla-ch hat in der FG Datenbank ein Team (>4P.) welches sich mit der Thematik befasst. Das Commitment für die Storry ist da. Neben unterschiedlichen Interessenvertretungen aus dem Jubla-Umfeld sind auch explizite Kenntnisse und auch Eigenleistungen vorhanden.

Siehe Erweiterung für die Verbindung zwischen Nextcloud Gruppen und Hitobito Rollen
nextcloud groups unique for group and role
https://github.com/bergerar/hitobito_jubla/tree/nextcloud_groups

**Comment by richardjubla** [comment]
Feature soll im Verlauf vom Dezember auf Stage-Umgebung ankommen.

**Comment by richardjubla** [comment]
Nur als Info: Es gibt auch Informationen zu Nextcloud  im Hitobito "development kit" https://github.com/hitobito/development/#nextcloud

**Comment by richardjubla** [comment]
Nur als Info: Eine Nextcloud Instanz (von der Stange) exklusiv für Testzwecke steht auf Seiten Jubla/FG Datenbank bereit.

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger

Wir müssen davon ausgehen, dass Eine Nextcloud Instanz (von der Stange) noch angepasst werden muss, damit es mit Hitobito verbunden werden kann. Bitte deshalb diese Informationen bereitstellen.

**Comment by kronn** [comment]
Hoi @richardjubla 

> Unsere Test-Nexcloud meldet:
> 
> `Impossible to decode OIDC token:Error: kid must be provided in JWT header. `
> 
> Deshalb frage ich mit Bezug auf das "Manual": Wurde das JWT-Signing eingerichtet?

Ja, es ist ein JWT-Signing-Key sowohl in der integration als auch in der production vorhanden und entsprechend verlinkt. Daran sollte es zumindest nicht liegen.

**Comment by carlobeltrame** [comment]
Die Einstellungen für das native Nextcloud OIDC Plugin könnten hier herausgelesen und adaptiert werden:
https://github.com/hitobito/development/blob/master/nextcloud/setup/setup.sh#L31..L38
Welche Einstellungen welchen deutschen Namen in eurem Nextcloud UI haben müsst ihr halt anhand der technischen Bezeichnungen zuordnen. Oder den hitobito-Nextcloud Dev Setup lokal starten und die Einstellungen dort rauslesen.

**Comment by richardjubla** [comment]
> Die Einstellungen für das native Nextcloud OIDC Plugin könnten hier herausgelesen und adaptiert werden: https://github.com/hitobito/development/blob/master/nextcloud/setup/setup.sh#L31..L38 Welche Einstellungen welchen deutschen Namen in eurem Nextcloud UI haben müsst ihr halt anhand der technischen Bezeichnungen zuordnen. Oder den hitobito-Nextcloud Dev Setup lokal starten und die Einstellungen dort rauslesen.

Danke für deinen Beitrag zu diesem Ticket, @carlobeltrame. Da ich nicht weiss ob du dich auf etwas spezifisches beziehst gebe ich ein Update unserer Situation:

Die Verbindung zwischen Hitobito und Nextcloud "funktioniert" in der Stage-Umgebung: Ein Profil welches an beiden Orten angelegt wird (Nextcloud/Hitobito), kann sich aus Hitobito heraus direkt in der Nextcloud anmelden. 

Für das "Rollen/Gruppenmapping" habe ich folgende Informationen:
- Die 7 Zeilen aus "Setup einer mit hitobito integrierten NextCloud-Instanz.md" zum Klassen-Attribut nextcloud_group
- Die Commits im SKV Wagon bei denen ich davon ausgehe, dass wir diese sinngemäss übernehmen könnten https://github.com/hitobito/hitobito_skv/commit/bfbfceb85c679abd95143aacad55f53b9789a5c6 
-  Den Fork von Armin https://github.com/bergerar/hitobito_jubla/tree/nextcloud_groups 


Hier meine Gedanken zu den Rollen:
- Zugang zu Nextcloud sollen "nur" aktive Vereinsmitglieder haben. Konkret sind das zum Beispiel Vorstand, Leiter*innen. Präses oder Coach. Nicht aber Kinder, Eltern oder Externe Kontakte. So wenig Accounts wie nötig. Öffentliche oder Netzwerk-Bedürfnisse für erweiterte Zielgruppen sind nicht über jubla.db/Nextcloud zu lösen. 
-  Minimal wären somit zwei "Gruppen" für den "Vorstand" und die "Aktivmitglieder" nötig





Ebenen-Leitung/Vorstand (Nextcloud Zugang):
      * Scharleitung
      * Lagerleitung
      * Kassier/in
      * Adressverwaltung
      * Leitung
      * IT Support


Aktivmitglieder (Nextcloud Zugang):
      * Leiter*in
      * Mitglied
      * Coach
      * Präses
      * Stellenbegleitung

**Kein** Nextcloud Zugang:
      * Alle ohne Explizite Zuteilung/Rolle
      * Kind
      * Ehemalig
      * Extern
      * Versandadresse
      * etc.



![hitobito-nextcloud](https://github.com/hitobito/hitobito_jubla/assets/95908537/e955f3af-7af5-4a18-b0ba-d006bb680f6b)

**Comment by carlobeltrame** [comment]
Alles klar, ich sehe, die Anbindung funktioniert mal, sieht schon mal gut aus.

Was mit der aktuellen Version von hitobito bzw. der Nextcloud-Anbindung noch nicht möglich ist, ist hitobito-seitig einigen Personen den Zugang zu Nextcloud zu verweigern und es anderen zu gewähren. Diese Entscheidung, wer sich einloggen darf und wer nicht, sehen wir bisher auf Seite der konsumierenden OAuth Applikation, also auf Seite Nextcloud.

Der aktuelle "Workaround" ist, das Nextcloud so zu konfigurieren dass Personen ohne Nextcloud-Gruppen praktisch keine Rechte haben. Sie können sich dann zwar via hitobito in Nextcloud einloggen, aber dort nichts weiter machen, keine Dateien ablegen etc.

Mit dem Code von Armin kann dann hitobito-seitig programmiert werden[^1], dass nur gewisse hitobito-Personen gewisse Nextcloud-Gruppen bekommen, wenn sie sich via hitobito in Nextcloud einloggen.

Der Code von Armin ist in der heutigen Form nicht sehr selektiv: Er verwendet mehr oder weniger einfach die Gruppen-ID bzw. den Gruppentyp als Nextcloud-Gruppennamen. Ihr könntet mit diesem Stand arbeiten und in Nextcloud einfach nur manuell selektiv an diejenigen Nextcloud-Gruppen die ihr wollt Rechte vergeben (z.B. allen Nextcloud-Gruppen die auf "-Vorstand" enden Vorstands-Rechte geben). Oder ihr könntet Armins Code verfeinern, sodass die nötige Logik (z.B. nur eine Nextcloud-Gruppe Vorstand und eine Nextcloud-Gruppe Aktivmitglieder) von hitobito an Nextcloud übergeben werden, je nach dem welche Rollen die sich einloggende Person hat.

[^1]: Dass diese Logik in hitobito implementiert wird, ist aus Architektur-Sicht nicht konsistent mit dem obigen Grundsatz. Das wurde auch schon kritisiert, aber da das Nextcloud-Plugin derzeit keine erweiterten Mapping-Optionen bietet ist das aktuell die beste Lösung die wir haben.

**Comment by bergerar** [comment]
@richardjubla

Ich würde jeweils pro Recht eine eigene Gruppe in Nextcloud machen. Dann kann dann jede Organisation selber entscheiden und es ist klar wer Zugriff hat.

Das sieht dann in Nextcloud z.B so aus:
![Screenshot 2023-12-18 at 19-37-46 Active users - Users - Users - Nextcloud](https://github.com/hitobito/hitobito_jubla/assets/7525727/9cd884da-733f-4819-bda0-9f8d855d7ed8)

Ich habe noch meinen Vorschlag angepasst, damit die Nextcloud Gruppen nicht nur für Scharen sondern für alle Gruppen generiert werden. Habe dann auch einen Pull Request erstellt: https://github.com/hitobito/hitobito_jubla/pull/66

**Comment by richardjubla** [comment]
Wenn für eine Schar/Ebene die Verbindung zwischen Hitobito/Nextcloud "funktionieren" soll, sollte sie als technisch nicht versierte Organisation nicht davon ausgehen müssen, dass jedes Hitobito-Profil mit einem Login sich auch auf ihre Nextcloud Instanz anmelden kann. Diesen Umstand will ich (bei uns) weiterverfolgen. 
Wir werden die möglichen Ansätze in der "Architektur-Sicht", den Möglichkeiten zur Konfiguration einer Nextcloud-Instanz und der OpenID Connect-App gut wählen müssen.

**Comment by richardjubla** [comment]
**Abschlussbericht für diese Story nach ende des Inkrement:**

- Die Verbindung zwischen jubla.db und Nextcloud wurde von der FG Datenbank weiterverfolgt (Ebene Schar). Ein Pull Request steht https://github.com/hitobito/hitobito_jubla/pull/66. 
- FG Datenbank kennt wahrscheinlich die wichtigsten Faktoren (Technik, Kosten, Abhängigkeiten). Es bestehen aber noch Unsicherheiten und grosse Risiken im Bereich (Folge-)Kosten und dem Umstand, dass weder Hitobito noch Nextcloud zwischen den Ebenen/Gruppen unterscheiden kann. 
-FG Datenbank kann aktuell das Feature Nextcloud ohne Gruppen-Mapping sowohl auf Stage- wie Produktiv-Umgebung testen oder verwenden.
- Es gibt noch keine Dokumentation oder Schritt-für-Schritt Anleitung für Scharen (inkl. Hinweise für Nextcloud) / Erfolgt durch jubla/FG DB


**Weiter notwendige Schritte wären (Vorschlag für Pläne/DoD):**
- Pull Request https://github.com/hitobito/hitobito_jubla/pull/66 (Schätzung bekannt) umsetzten lassen
- Entweder muss Nextcloud stark «konfiguriert» werden oder die Schar muss damit rechnen, dass jedes jubla.db-Profil (inkl. Selbstregistrierung) ein Profil in der Nextcloud erstellen kann. Es beleibt ein entscheidender Aspekt unserer Lösung, dass eine Schar (Ebene/Gruppe) ihre eigene Nextcloud-Instanz ohne technisches Expertenwissen nutzen kann. Story: Als Schar/Gruppe kann ich sicherstellen, dass nur Menschen in meiner Gruppe/Ebene Zugang zu meiner Nextcloud-Instanz/Daten erhalten.
- Dokumentation oder Schritt-für-Schritt Anleitung für Scharen (inkl. Hinweise zu Nextcloud) wird durch die Fachgruppe Datenbank verfasst

**Comment by richardjubla** [comment]
Interner Hinweis: Sollen die Nextcloud Benutzer sich gegenseitig nicht sehen: https://help.nextcloud.com/t/benutzer-vor-anderen-benutzern-verstecken/20325/14


![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/091f9835-b852-4139-a735-a650f95af30f)

**Comment by richardjubla** [comment]
Update:


Anscheinend wurde die [Organization Hierarchy überarbeitet](https://github.com/hitobito/hitobito_jubla/commit/1e1cfe5542778fe528d6d61da051fc759a3480b1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). Dies hat Auswirkungen auf die übermittelten "Gruppen" zu Nextcloud.

Füher:
Nölliturm (TestSchar) - Eltern

Neu:
478_Group::FederalProfessionalGroup::Lead

(ID der Gruppe -> Nextcloud Test :: Gruppentyp -> Fachgruppe -> Rolle -> Leitung) 



Vermutung: Wäre das Feature produktiv eingesetzt worden, wäre der Login und die Nextcloud-Gruppen "kaputt" gegangen. Ein Admin müsste die Berechtigungen neu setzten bzw. migrieren.

**Comment by richardjubla** [comment]
Demo Konfiguration für Zugriffskontrolle zu Nextcloud über OpenID Connect Plugin


![Image](https://github.com/user-attachments/assets/e16844c8-0557-42a4-a5ff-c647c7de6589)


Kennung (max. 128 Zeichen): 
Client-ID
Geheime Zeichenkette des Clients
Erkennungsendpunkt: `https://jubla.puzzle.ch/.well-known/openid-configuration`
Benutzerdefinierter Endpunkt zum Beenden der Sitzung: `https://jubla.puzzle.ch/oidc/logout`
Anwendungsbereich: `openid email nextcloud`

Extra Claims


Benutzer-ID-Mapping: `sub`
Kontingent-Mapping: `quota`
Gruppen-Mapping: `groups`



**Authentifizierungs- und Zugriffskontrolleinstellungen**
![Image](https://github.com/user-attachments/assets/68867e1f-3743-48e7-9b98-0d4a33e96342)

Eindeutige Benutzer-ID verwenden: Nein -> Damit wird der Kontoname gleich der jubla.db-ID (jubla.puzzle.ch/groups/GRID/people/ZAHL )

Providerkennung als Präfix für IDs verwenden: Kennung+Benutzer-ID = hitobito-ZAHL

Gruppen-Whitelist-Regex `/^65_Group/`



Mit diesen Einstellungen kann sich nur ein Profil anmelden, wenn es von hitobito (der jubla.db) eine Rolle in der Gruppe mit der ID 65 hat. (Siehe https://jubla.puzzle.ch/groups/65 -> Jubla Luzern)

**Comment by richardjubla** [comment]
**use_refresh_token**


Ausgangslage: Aktuell gibt jubla.db über OAuth nur ein access_token mit 2h Gültigkeit heraus, kein refresh_token (use_refresh_token: false, [settings.yml:270](vscode-webview://0ka4duuk1bjhifpgoq63hnehv0m95viobn51k062rdq7ac4ok3mb/git/hitobito/jubla/app/hitobito/config/settings.yml#L270)). Nach 2h muss sich der Client zwingend neu über den vollen interaktiven Login-Flow anmelden.

Was neu dazukommt: Das Feature aus [hitobito_pbs#463](https://github.com/hitobito/hitobito_pbs/issues/463) wurde nach hitobito-Core verschoben ([hitobito/hitobito#4275](https://github.com/hitobito/hitobito/issues/4275)) und ist im lokalen Code bereits als Commit 894a0c3ff vorhanden — die Möglichkeit existiert also, ist aber bei uns noch ausgeschaltet (kein jubla-Override). PBS selbst hat es aktiviert, aber mit refresh_token_expires_in: 7.days — bewusst kürzer als der Core-Default von 180 Tagen.

Warum das für Nextcloud relevant sein könnte: Ein Refresh-Token erlaubt einem Client (Nextcloud), den Zugriff im Hintergrund zu verlängern, ohne dass die Person nochmal den interaktiven Browser-Login durchläuft. Genau dieser interaktive Login ist aber der Ort, an dem user_oidc (das Nextcloud-Plugin) den Gruppen-Sync (provisionUserGroups) auslöst.

Praktische Konsequenz, falls aktiviert: Die Zeitspanne, bis eine beendete Rolle tatsächlich zu einem Gruppen-Entzug in Nextcloud führt, würde sich von "nächster Login" (Stunden bis wenige Tage) auf potenziell Monate (bis zu 180 Tage bei Core-Default) verlängern.

Empfehlung: Falls ihr das für die Nextcloud-Integration aktivieren wollt (z.B. für unterbrechungsfreie Desktop-/Mobile-Sync-Clients), dann:

refresh_token_expires_in explizit kurz setzen (analog PBS: 7 Tage), nicht den 180-Tage-Default übernehmen.
Klären, ob Nextcloud-Setup den Gruppen-Sync auch beim stillen Token-Refresh erneut auslöst.

**Comment by carlobeltrame** [comment]
Hoi @richardjubla, ein paar Korrekturen dazu.

> Ausgangslage: Aktuell gibt jubla.db über OAuth nur ein access_token mit 2h Gültigkeit heraus, kein refresh_token (use_refresh_token: false, settings.yml:270). Nach 2h muss sich der Client zwingend neu über den vollen interaktiven Login-Flow anmelden.

> die Möglichkeit existiert also, ist aber bei uns noch ausgeschaltet (kein jubla-Override).

Stimmt beides nicht; seit dem Release gestern ist das bei euch auch in Produktion aktiv. Auf Zeile 270 im Core settings.yml steht etwas anderes, auf Zeile 269 ist standardmässig `use_refresh_token: true`. Es gibt bisher keine Overrides im youth oder jubla Wagon dazu, diese wären aber bei Bedarf möglich.

> Core-Default von 180 Tagen

Stimmt ebenfalls nicht, dies wurde gleich zusammen mit dem Feature im Core von 180 auf 7 Tage heruntergesetzt.

> Empfehlung: Falls ihr das für die Nextcloud-Integration aktivieren wollt

Die Refresh Tokens muss man im user_oidc Plugin trotzdem noch aktivieren. Sie werden nur genutzt, wenn man in den Plugin-Einstellungen die Option "Store login tokens" aktiviert. Falls ihr den Refresh also nicht wollt, könnt ihr einfach nextcloud-seitig diese Option deaktivieren.

> Klären, ob Nextcloud-Setup den Gruppen-Sync auch beim stillen Token-Refresh erneut auslöst.

Scheinbar ist das nicht so, also der Gruppen-Sync passiert NICHT, wenn das refresh token benutzt wird. Könnte man bei Nextcloud als neue Option für das Plugin contributen.

Alternativ könntet ihr aufs [Cevi-Plugin](https://github.com/cevi/nextcloud-hitobito-login) umsteigen, dieses kann vermutlich inzwischen mehr und kann flexibler angepasst werden als das nextcloud user_oidc Plugin. Refresh Tokens sind dort noch gar nicht unterstützt, und das Problem wäre damit hinfällig.
