### ISSUE TITLE
Mitglieder werden mit Gruppen gelöscht

### ISSUE THREAD

**Issue by 01000101-01100011-01101000-01101111** [hitobito/hitobito_jubla#67]
Beim Löschen von Untergruppen einer Schar werden die Teilnehmer (auch Ehemalige) entfernt, anstatt, dass diese die Rolle "Ehemalig" erhalten. Damit können Gruppen nicht wiederhergestellt werden bzw. haben dann keine Teilnehmer mehr.

**Comment by richardjubla** [comment]
Grundsätzlich sind immer alle Anpassungen der  **Profile/Rollen** in einer Gruppe vor einer Löschung zu tätigen.

Schar/Ebenen können nur gelöscht werden, wenn keine Profile/Rollen mehr vorhanden sind. Untergruppen können gelöscht werden, selbst wenn sich darin noch Profile/Rollen befinden. Es ist nicht vorgesehen oder einer Funktion der jubla.db, dass eine solche Löschung rückgängig gemacht werden kann. (Die Löschung wir aber im Log der Profile vermerkt und ist somit nachvollziehbar).
Es ist auch nicht vorgesehen, dass Profile die Rolle Ehemalig erhalten, wenn sie mit einer (der letzten) Gruppe mit gelöscht werden. 

Hier die Regeln, nach denen die Rolle "Ehemalig" vergeben wird:
- Die letzte aktive Rolle der Person in dieser Gruppe und Ebene wird gelöscht 
- Die gelöschte Rolle war mindestens 7 Tage alt (sonst wird die Rolle bei der Löschung als "Versehen" angesehen und komplett gelöscht ohne eine Ehemaligenrolle zu erstellen oder Mails zu versenden) 
- Die gelöschte Rolle war nicht in einer Kindergruppe 
  - Falls die Rolle doch in einer Kindergruppe war, muss die Person mindestens 15 Jahre alt sein. Ist kein Geburtsdatum gesetzt, wird auch keine Ehemaligen-Rolle erstellt und kein Mail versendet 
- Es hat vorher noch keine Ehemaligenrolle in dieser Ebene existiert 
- Die Ehemaligenrolle kann erfolgreich gespeichert werden 
- Die Person hat eine Haupt-E-Mailadresse 
- 1 Tag ist seit dem Löschen der Aktivrolle vergangen, und die Ehemaligenrolle existiert immer noch

**Comment by richardjubla** [comment]
> Dann ist es ein Fehler, dass alte gelöschte Kindergruppen ihre Mitglieder behalten haben und die Auflistung der gelöschten Untergruppen der Schar ist "nutzlos", da diese nur ohne Mitglieder reaktiviert werden können?

Ich kenne die genauen Beweggründe nicht. Ich halte es aber für "besser", wenn keine vergessenen und unbewirtschafteten Profile in gelöschten Gruppen liegen bleiben können. Die Datenbank hat keinen Archiv-Auftrag und ist primär darauf ausgelegt den aktuellen Zustand der Schar/Vereins abzubilden. Hier spielt auch das Thema Datenschutz (Datensparsamkeit) eine Rolle. Der Entzug der Rollen bedeutet auch, dass die Berechtigungen, Sichtbarkeit und Kontaktrelevanz für dieses Profil entfernt werden. Es wäre nicht korrekt, wenn Kinder/Mitglieder damit automatisch (durch eine Löschung) dem Ehemaligenwesen zugeordnet werden oder Personen mit Kontaktrelevanz diese in der gelöschten Gruppe behalten. 

Evtl. interessiert dich, das zu diesem Thema sonnst noch zu "sagen" ist:
- Es gibt/gab Bestrebungen das versehentliche Löschen zu erschweren:  https://github.com/hitobito/hitobito_jubla/issues/51
- Es gibt Überlagerungen was mit Profilen (ohne Rollen) mit der Zeit passieren soll: https://github.com/hitobito/hitobito/issues/1299
