### ISSUE TITLE
Selbstregistrierung Gruppe/Event/Elternzugang

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#75]
**Story:**
-
Als Verein (Schar/Gruppe/Ebene) bin ich verantwortlich für die mit mir interagierenden Menschen und deren Profile auf der Mitgliederdatenbank (jubla.db). Sofern ich eine Selbstregistrierung oder Anmeldung in meinen Verein (Schar/Gruppe/Ebene) oder einen Event (Anlass/Kurs/Lager) anbiete, will (und muss) ich die Einsicht und Kontrolle über diese Profile und Anmeldungen haben. Zudem will ich bestimmte Informationen von den interagierenden Menschen abfragen, damit ich sie einfach(er) kontaktieren kann. 

Als Schar sind mir folgende Methoden zur Interaktion bekannt:
- Externe Anmeldung für Schar/Gruppe/Ebene 
- Externe Anmeldung für Event (Anlass/Kurs/Lager)
- Mit bestehendem Profil durchgeführte Registrierung für Schar/Gruppe/Ebene (neues Mitglied/Externer-Kontakt in meinem Verein)
- Mit bestehendem Profil durchgeführte Registrierung für Event (Anlass/Kurs/Lager) 

Als Verein benötige ich demzufolge:
- Jedes Profil durch eine Anmeldung/Selbstregistrierung muss dazu führen, dass eine Rolle (Extern) auf der Ebene/Gruppe entsteht oder die Gruppen-Leitung oder Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil entsteht.
- Eltern wie auch Kinder (Elternzugang) aus Anmeldung/Selbstregistrierung müssen ebenfalls eine Rolle (Extern/Kind) auf der Ebene/Gruppe erhalten und müssen durch die Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil erhalten.
- Eine Event-Leitung muss sehen können, dass es bei einer Anmeldung um ein verwaltetes Kinder-Profil handeln könnte und muss auch deren Eltern kontaktieren können. (Die Eltern gehen davon aus, dass Sie und Ihr Kind vom Verein verwaltet werden und die Informationen insbesondere für Events auch für Notfälle/Rückfragen/etc. genutzt werden können.) Siehe: https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946
- Das Formular für die Selbstregistrierung in eine Schar/Gruppe/Ebene muss mehr Informationen abfragen.
-- Vorname (ja, zwingend)
-- Nachname (ja, zwingend)
-- Firmenname (nein, nicht anzeigen)
-- Firma (nein, nicht anzeigen)
-- Adresse (ja, optional)
-- PLZ/Ort (ja, optional)
-- Telefonnummern (ja, optional)
-- Haupt-E-Mail (ja, zwingend)

**Aspekte:**
- https://github.com/hitobito/hitobito/issues/2373 
- https://github.com/hitobito/hitobito/issues/2357
- https://github.com/hitobito/hitobito/issues/103#issuecomment-1912151288
- https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946
- Falls technisch notwendig, kann der Status und die Rolle von Verwalteten/Erstellten/Angemeldeten Kindern für Events (Anlässe/Lager) auf Teilehmer*in oder "Extern" angepasst werden. Dadurch sind sie nicht mehr wie die Kinder-Rolle "geschützt", aber durch die Ebene/Event-Leitung verwaltbar. Ähnlich funktioniert es, wenn sich ein Profil mit der Rolle "Kind" für ein Lager anmeldet. 
Ein Kind (als Mensch) kann sich durchaus durch Selbstregistrierung in eine Ebene/Gruppe anmelden. Die Leitung musss sie dann in ihre Vereinsstruktur integrieren und mit der Rolle "Kind" versehen. 

**Akzeptanzkriterien:**

- Verein (Schar/Gruppe/Ebene) hat die Verantwortung und Kontrolle über interagierende oder erstellte Profile/Anmeldungen auf ihre eigene Schar/Gruppe/Ebene und Events (zB. Lager/Anlässe).
- Formulare, Berechtigungen und 
- Die Implementierung stellt eine reale Zeitersparnis und Mehrwert für sowohl den Menschen welcher sich neu Anmelden möchte wie auch für den verantwortlichen Verein. 
- Es ist nicht möglich, durch Selbstregistrierung an Informationen oder Rechte zu kommen, die nicht öffentlich sind. Siehe: https://github.com/hitobito/hitobito/issues/2357

**Defintion of Done**

- Alle Akzeptanzkriterien wurden erfüllt oder eine alternative gefunden
- Die Implementierung wurde getestet und als fehlerfrei bestätigt.
- Die Dokumentation/Tests wurde(n) aktualisiert.
- Die Benutzer wurden über das neue Feature informiert.

**Comment by ThomasEllenberger** [comment]
Einige Inputs meinerseits, zur Klärung was eine Offerte von uns alles abdecken würde:


> Als Schar sind mir folgende Methoden zur Interaktion bekannt:
>
>     * Mit bestehendem Profil durchgeführte Registrierung für Schar/Gruppe/Ebene (neues Mitglied/Externer-Kontakt in meinem Verein)

Dies ist stand Heute nicht möglich.
Habe ich bereits ein Profil, kann ich mich mit der gleichen Emailadresse nicht bei einer anderen Gruppe, welche die Selbstregistrierung aktiviert hat, anmelden.
Sobald eine Person in Hitobito existiert müssen dieser immer Personen mit entsprechenden Rechten weitere Rollen hinzufügen.


> Als Verein benötige ich demzufolge:
> 
>     * Jedes Profil durch eine Anmeldung/Selbstregistrierung muss dazu führen, dass eine Rolle (Extern) auf der Ebene/Gruppe entsteht oder die Gruppen-Leitung oder Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil entsteht.
> 
 Bei einer Selbstregistration auf einer Gruppe kann in den Einstellungen definiert werden welche Rolle die neue Person erhalten soll.
 Bei einer Externen Registration auf einen Anlass erhält eine Person automatisch auch eine Rolle "Extern" auf der gleichen Gruppe (Jubla spezifisches Feature).
Entsprechend sehe ich diesen Punkt als bereits erfüllt und in der Offerte nicht enthalten.

>     * Eltern wie auch Kinder (Elternzugang) aus Anmeldung/Selbstregistrierung müssen ebenfalls eine Rolle (Extern/Kind) auf der Ebene/Gruppe erhalten und müssen durch die Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil erhalten.

Bei der Jubla ist der Teil des Elternzugangs, durch welchen Eltern selbst neue Kinder erstellen und an Anlässen anmelden können deaktiviert. Entsprechend kann sich niemand als Eltern oder Kinder registrieren, sondern einfach als ein Benutzer. Es zieht also in jedem Fall das Verhalten von Punkt 1. Erst durch die Verknüpfung zweier accounts durch einen Addressverwalter werden diese zu Eltern und Kindern. In diesem Moment müssen sie jedoch zwingend bereits eine Rolle haben.  
Entsprechend sehe ich diesen Punkt als bereits erfüllt und in der Offerte nicht enthalten.

>     * Eine Event-Leitung muss sehen können, dass es bei einer Anmeldung um ein verwaltetes Kinder-Profil handeln könnte und muss auch deren Eltern kontaktieren können. (Die Eltern gehen davon aus, dass Sie und Ihr Kind vom Verein verwaltet werden und die Informationen insbesondere für Events auch für Notfälle/Rückfragen/etc. genutzt werden können.) Siehe: [Elternzugang: Gefundene Bugs & gewünschte Nacharbeiten hitobito#2125 (comment)](https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946)

Bei der Anmeldung ist auf dem Profil des Teilnehmenden nur dann ersichtlich ob Kinder oder Verwalter vorhanden sind, wenn die Event-Leitung diese Profile auch ausserhalb des Kurses sehen dürfte.
Diese Anforderung ist heute entsprechend nicht erfüllt und wird in die Offerte aufgenommen.
Frage: Meines Erachtens gibt es hier drei Stufen der Sichtbarkeit.
1. Es muss nur ersichtlich sein dass ein Teilnehmer einen Verwalter/ein Kind hat.
2. Es muss ersichtlich sein wer dieser Verwalter ist (Name/Vorname)
3. Die Event-Leitung muss auch Leserechte auf das entsprechende Profil erhalten um dieses einsehen zu können
Was wäre heir gewünscht?

>     * Das Formular für die Selbstregistrierung in eine Schar/Gruppe/Ebene muss mehr Informationen abfragen.
>       -- Vorname (ja, zwingend)
>       -- Nachname (ja, zwingend)
>       -- Firmenname (nein, nicht anzeigen)
>       -- Firma (nein, nicht anzeigen)
>       -- Adresse (ja, optional)
>       -- PLZ/Ort (ja, optional)
>       -- Telefonnummern (ja, optional)
>       -- Haupt-E-Mail (ja, zwingend)

Anforderung soweit klar, wird in die Offerte mit hineinfliessen.



> 
> **Aspekte:**
> 
>     * [Selbstregistrierung: Neuer Bug hitobito#2373](https://github.com/hitobito/hitobito/issues/2373)

Verhalten konnte ich so nicht nachstellen.
Stand heute nicht in Offerte mit drin.

>     * [Externe Registrierung für Rollen mit Contact_Data hitobito#2357](https://github.com/hitobito/hitobito/issues/2357)

Anforderungen klar, werden wir in die Offerte mit aufnehmen.

>     * [Für Coaches und Leiterkursbetreuer betreute Kurse auf der Personenübersicht zeigen hitobito#103 (comment)](https://github.com/hitobito/hitobito/issues/103#issuecomment-1912151288)

Die Anforderungen sind für mich hier nicht klar.
Ist das Ziel, dass Personen mit der Rolle "Extern" die Events in welchen sie eine Rolle haben ebenfalls auf Ihrer Profilübersicht angezeigt bekommen?
Stand heute nicht in Offerte mit drin.

>     * [Elternzugang: Gefundene Bugs & gewünschte Nacharbeiten hitobito#2125 (comment)](https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946)

Stand heute ist es in der Jubla Umgebung nicht möglich dass ein Account ein ihm Zugewiesenes Kind selbst erstellt.
Dieses Problem besteht meines Erachtens aktuell also nicht mehr.
Stand heute nicht in Offerte mit drin.

>     * Falls technisch notwendig, kann der Status und die Rolle von Verwalteten/Erstellten/Angemeldeten Kindern für Events (Anlässe/Lager) auf Teilehmer*in oder "Extern" angepasst werden. Dadurch sind sie nicht mehr wie die Kinder-Rolle "geschützt", aber durch die Ebene/Event-Leitung verwaltbar. Ähnlich funktioniert es, wenn sich ein Profil mit der Rolle "Kind" für ein Lager anmeldet.
>       Ein Kind (als Mensch) kann sich durchaus durch Selbstregistrierung in eine Ebene/Gruppe anmelden. Die Leitung musss sie dann in ihre Vereinsstruktur integrieren und mit der Rolle "Kind" versehen.

Anforderung ist mir unklar, können wir gerne einmal billateral anschauen.
Stand heute nicht in Offerte mit drin.

**Comment by richardjubla** [comment]
> Einige Inputs meinerseits, zur Klärung was eine Offerte von uns alles abdecken würde:
> 
> > Als Schar sind mir folgende Methoden zur Interaktion bekannt:
> > ```
> > * Mit bestehendem Profil durchgeführte Registrierung für Schar/Gruppe/Ebene (neues Mitglied/Externer-Kontakt in meinem Verein)
> > ```
> 
> ~Dies ist stand Heute nicht möglich. Habe ich bereits ein Profil, kann ich mich mit der gleichen Emailadresse nicht bei einer anderen Gruppe, welche die Selbstregistrierung aktiviert hat, anmelden. Sobald eine Person in Hitobito existiert müssen dieser immer Personen mit entsprechenden Rechten weitere Rollen hinzufügen.~ Edit: Heute wieder etwas neues gelernt. Das ist tatsächlich im Core möglich.
> 
> > Als Verein benötige ich demzufolge:
> > ```
> > * Jedes Profil durch eine Anmeldung/Selbstregistrierung muss dazu führen, dass eine Rolle (Extern) auf der Ebene/Gruppe entsteht oder die Gruppen-Leitung oder Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil entsteht.
> > ```
> 
> Bei einer Selbstregistration auf einer Gruppe kann in den Einstellungen definiert werden welche Rolle die neue Person erhalten soll. Bei einer Externen Registration auf einen Anlass erhält eine Person automatisch auch eine Rolle "Extern" auf der gleichen Gruppe (Jubla spezifisches Feature). Entsprechend sehe ich diesen Punkt als bereits erfüllt und in der Offerte nicht enthalten.
> 
> > ```

Das ist gemäss unseren Test so nicht der Fall: Bei einer Anmeldung von einem Kind für einen Event (Feature Elternzugang) bekommt das angemeldete "Kind"-Profil keine Rolle. Dieses Profil (und der Verwalter) ist durch den Event-Veranstalter nicht sichtbar. Ebenfalls fehlt im Event die Information, dass es sich bei der Anmeldung um ein Profil handelt welches durch einen Verwalter angemeldet wurde. (Der Verwalter "haftet" ja für die Anmeldung, wird hier weiter sichtbar: https://github.com/hitobito/hitobito/issues/2404)
Zweitens wird bei einer Selbstregistration auf einer Gruppe (externe Registrierung) in erster Linie ein neues Profil erstellt. Das sollte nicht passieren. Aktuell ist die (externe) Selbstregistrierung für bestehende Profile defekt:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/b590cfd1-5204-4c91-bef9-f43758cf6fe7)

Bei einer externen Registrierung wird ein externes Profil erstellt sowie auch bei Personen, die sich noch einloggen müssen (Anmelden und einschreiben). 
https://github.com/hitobito/hitobito/issues/2373
Schafft jemand mit Profil dennoch sich "Anmelden und Einzuschreiben", entsteht ein neues Profil/Account (mit Name Vorname) und eine Rolle "Extern" für das bestehende Profil"


> > * Eltern wie auch Kinder (Elternzugang) aus Anmeldung/Selbstregistrierung müssen ebenfalls eine Rolle (Extern/Kind) auf der Ebene/Gruppe erhalten und müssen durch die Event-Leitung mindestens Lese-Rechte auf das angemeldete Profil erhalten.
> > ```
> 
> Bei der Jubla ist der Teil des Elternzugangs, durch welchen Eltern selbst neue Kinder erstellen und an Anlässen anmelden können deaktiviert. Entsprechend kann sich niemand als Eltern oder Kinder registrieren, sondern einfach als ein Benutzer. Es zieht also in jedem Fall das Verhalten von Punkt 1. Erst durch die Verknüpfung zweier accounts durch einen Addressverwalter werden diese zu Eltern und Kindern. In diesem Moment müssen sie jedoch zwingend bereits eine Rolle haben. Entsprechend sehe ich diesen Punkt als bereits erfüllt und in der Offerte nicht enthalten.
> 
> > ```

Diese Aussage ist für uns nicht korrekt: Anmeldungen durch Verwalter für ihre verwalteten Profile (Kinder), führen nicht zum Verhalten von Punkt 1. Es bestehen zwar Rollen, diese sind aber durch die Event-Leitung nicht nachvollziehbar.
Nochmals: Als Event-Leitung muss ich Menschen die sich bei mir anmelden vollumfänglich "verstehen" können. Bei einer Anmeldung mit einer Verwalter-Beziehung muss ich über diese Beziehung informiert sein und dies in der Anmeldung unmissverständlich sehen. 


> > * Eine Event-Leitung muss sehen können, dass es bei einer Anmeldung um ein verwaltetes Kinder-Profil handeln könnte und muss auch deren Eltern kontaktieren können. (Die Eltern gehen davon aus, dass Sie und Ihr Kind vom Verein verwaltet werden und die Informationen insbesondere für Events auch für Notfälle/Rückfragen/etc. genutzt werden können.) Siehe: [Elternzugang: Gefundene Bugs & gewünschte Nacharbeiten hitobito#2125 (comment)](https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946)
> > ```
> 
> Bei der Anmeldung ist auf dem Profil des Teilnehmenden nur dann ersichtlich ob Kinder oder Verwalter vorhanden sind, wenn die Event-Leitung diese Profile auch ausserhalb des Kurses sehen dürfte. Diese Anforderung ist heute entsprechend nicht erfüllt und wird in die Offerte aufgenommen. Frage: Meines Erachtens gibt es hier drei Stufen der Sichtbarkeit.
> 
> 1. Es muss nur ersichtlich sein dass ein Teilnehmer einen Verwalter/ein Kind hat.
> 2. Es muss ersichtlich sein wer dieser Verwalter ist (Name/Vorname)
> 3. Die Event-Leitung muss auch Leserechte auf das entsprechende Profil erhalten um dieses einsehen zu können
>    Was wäre heir gewünscht?
> 
> > ```
> > * Das Formular für die Selbstregistrierung in eine Schar/Gruppe/Ebene muss mehr Informationen abfragen.
> >   -- Vorname (ja, zwingend)
> >   -- Nachname (ja, zwingend)
> >   -- Firmenname (nein, nicht anzeigen)
> >   -- Firma (nein, nicht anzeigen)
> >   -- Adresse (ja, optional)
> >   -- PLZ/Ort (ja, optional)
> >   -- Telefonnummern (ja, optional)
> >   -- Haupt-E-Mail (ja, zwingend)
> > ```
> 
> Anforderung soweit klar, wird in die Offerte mit hineinfliessen.
> 
> > **Aspekte:**
> > ```
> > * [Selbstregistrierung: Neuer Bug hitobito#2373](https://github.com/hitobito/hitobito/issues/2373)
> > ```
> 
> Verhalten konnte ich so nicht nachstellen. Stand heute nicht in Offerte mit drin.
> 
Bitte direkt in der Issue vermerken. Aus unserer Sicht klar ein bug/fehlverhalten. 

> > ```
> > * [Externe Registrierung für Rollen mit Contact_Data hitobito#2357](https://github.com/hitobito/hitobito/issues/2357)
> > ```
> 
> Anforderungen klar, werden wir in die Offerte mit aufnehmen.
> 
> > ```
> > * [Für Coaches und Leiterkursbetreuer betreute Kurse auf der Personenübersicht zeigen hitobito#103 (comment)](https://github.com/hitobito/hitobito/issues/103#issuecomment-1912151288)
> > ```
> 
> Die Anforderungen sind für mich hier nicht klar. Ist das Ziel, dass Personen mit der Rolle "Extern" die Events in welchen sie eine Rolle haben ebenfalls auf Ihrer Profilübersicht angezeigt bekommen? Stand heute nicht in Offerte mit drin.

Es geht um den gemeldeten Bug (als Kommentar). Auf der Personenübersicht gibt es aber keinen Grund, im  Event als betreuten Kurs (Meine Betreuungen) anzuzeigen. Aber ja, es wäre ein interessantes Feature, die Events für verwaltete Profile auf der Profilübersicht angezeigt bekommen. (Soll aber nicht Bestandteil der Anforderung/Offerte sein)

> 
> > ```
> > * [Elternzugang: Gefundene Bugs & gewünschte Nacharbeiten hitobito#2125 (comment)](https://github.com/hitobito/hitobito/issues/2125#issuecomment-1623548946)
> > ```
> 
> Stand heute ist es in der Jubla Umgebung nicht möglich dass ein Account ein ihm Zugewiesenes Kind selbst erstellt. Dieses Problem besteht meines Erachtens aktuell also nicht mehr. Stand heute nicht in Offerte mit drin.

Dieser Aspekt ist dennoch für uns wichtig. Wir möchten insbesondere den Stand des 2. Teils des Elternzugangs, die Funktionen der externen Registrierung wie auch die aktuellen Entwicklungen beim SAC/CAS aufnehmen können. Wir erwarten, dass unsere Aspekte im Kontext von gemeinsamen Features und Abhängigkeiten (Core/Youth/Elternzugang) von euch gesehen, vermittelt und gelöst werden.

> 
> > ```
> > * Falls technisch notwendig, kann der Status und die Rolle von Verwalteten/Erstellten/Angemeldeten Kindern für Events (Anlässe/Lager) auf Teilehmer*in oder "Extern" angepasst werden. Dadurch sind sie nicht mehr wie die Kinder-Rolle "geschützt", aber durch die Ebene/Event-Leitung verwaltbar. Ähnlich funktioniert es, wenn sich ein Profil mit der Rolle "Kind" für ein Lager anmeldet.
> >   Ein Kind (als Mensch) kann sich durchaus durch Selbstregistrierung in eine Ebene/Gruppe anmelden. Die Leitung musss sie dann in ihre Vereinsstruktur integrieren und mit der Rolle "Kind" versehen.
> > ```
> 
> Anforderung ist mir unklar, können wir gerne einmal billateral anschauen. Stand heute nicht in Offerte mit drin.

Versuche etwas mehr Kontext zu gegeben: Kinder und Kinder-Gruppen sind und sollen auf der jubla.db besonders geschützt. Sie sind zu Beispiel nur eingeschränkt sichtbar. Im Kontext von Event-Anmeldungen oder bei der Verwaltung von/durch "Verwalter/Elternzugang" wird dieser Schutz teilweise bewusst aufgebrochen: Ein Kind welches in ein Lager geht oder an einen Event angemeldet wird, wird mit der Rolle "Teilnehmer" nicht mehr mit der Rolle "Kind" geschützt. Dieses verhalten ist aus meiner Sicht "notwendig" und so gewollt. Es ist also nicht vorgesehen, dass die Rolle "Kind" für die die Abläufe der (externen) Anmeldung oder Verwalter-Funktionen verwendet wird.

**Comment by ThomasEllenberger** [comment]
Ich versuche mich hier einmal in einer Zusammenfassung, respektive neuen Anforderung für dieses Issue:

### Sicht auf Teilnehmendendaten

#### Anforderung:
Meldet sich eine Person bei der Jubla an einen Anlass an, so muss die Anlassverantwortliche diese Person in Gänze sehen können.

#### Bisher:
Hier gibt es bei der Jubla einen Automatismuss dass sich eine Person welche sich auf einen Anlass Anmeldet und noch kein Hitobito Profil hat automatisch zur Kursrolle auch noch eine Rolle "Extern" auf der jeweiligen Ebene erhält. Hat eine Person bereits eine Rolle in Hitobito, so zieht dieser Automatismus nicht mehr.

#### Neu: 
##### Option 1:
Neu sollen auch Personen welche bereits eine Rolle in Hitobito haben, beim Anmelden an einen Event immer auch eine Rolle "Extern" auf dem jeweiligen Layer bekommen. Dies ungeachtet davon welche Rollen sie bereits haben, oder ob sie sich selbst anmelden, oder durch einen Verwalter*innen Account angemeldet werden.
Bekanntes Problem ist hier dass dadurch Kinder für Personen Sichtbar werden, welche ansonnsten keine Sicht auf diese haben (und es auch bleiben, da sie nach Abschluss des Kurses weiterhin die Rolle "Extern" behalten).
##### Option 2:
Die Sichtbarkeit von Personen auf Kursen für die Kursrollen "Hauptleitung" und "Leitung" werden erweitert.
Neu sollen die Eventrollen "Hauptleitung" und "Leitung" auf allen Personen im Kurs ihre Verwalter- und Kinder-Accounts sehen. Hat eine Person Verwalter- oder Kinderaccounts sollen Kursleitende auch auf diese Accounts Leserechte haben.

#### Anmerkung:
Ich würde klar Option 2 bevorzugen. Dadurch erhalten Kinder keine Rollen in diversen Gruppen wo sie einmal an einem Anlass teilgenommen haben durch welche sie anschliessend für deutlich mehr Personen sichtbar sind.

### Rollenvergabe bei Selbstregistrierung.

#### Anforderungen:
Ist auf einer Gruppe die Selbstregistration aktiv können sich auch Personen einschreiben welche bereits ein Hitobito Profil haben. Die Rolle welche dabei vergeben wird hängt von der bei der Selbstregistrierung ausgewählten Rolle ab. Die Rolle wird vergeben unabhängig davon, ob eine Person bereits ein Hitobito Profil hat oder nicht.

##### Abgrenzung:
Von diesem Issue ausgeschlossen ist der Bug welcher in [#2373](https://github.com/hitobito/hitobito/issues/2373) beschreiben wird. Stand heute gehen wir davon aus, dass dieser behoben ist.
Ebenfalls von diesem Issue ausgeschlossen ist alles was mit dem Elternzugang zu tun hat. Stand heute können sich Personen nur selbst in eine Gruppe einschreiben, nicht aber die von ihnen verwalteten Accounts. Wäre dies gewünscht, so würde dies in einem separaten Issue umgesetzt.

##### Neu:
Ich sehe diesen Punkt vollumfänglich als erfüllt an. Meines Erachtens muss hier nichts erweitert werden.

### Erweiterung Formular zur Selbstregistrierung:

#### Anforderungen:
Die Jubla will die Pflichtfelder welche bei einer Selbstregistration erforderlich sind erweitern.

#### Bisher:
Bisher werden bei der Selbstregistration die folgenden Felder abgefragt:
- Vorname (Pflichtfeld)
- Nachname (Pflichtfeld)
- Firmenname
- Firma
- Haupt-E-Mail
- Datenschutzerklärung (Pflichtfeld)

##### Neu:
Neu sollen die folgenden Felder abgefragt werden:
- Vorname (Pflichtfeld)
- Nachname (Pflichtfeld)
- Adresse
- PLZ/Ort
- Telefonnummern
- Haupt-E-Mail (Pflichtfeld)
- Datenschutzerklärung (Pflichtfeld)

Nicht mehr angezeigt/abgefragt soll werden:
- Firmenname
- Firma



@richardjubla Bitte überprüfen und kommentieren.
PS: Solch verschatelte Issues sind für mich enorm aufwendig zum nachvollziehen und zur Offertenstellung. In Zukunft wären in solchen Fällen evtl. drei separate Issues zielführender.

**Comment by richardjubla** [comment]
**Hinweis zur Sichtbarkeit der Verwalter*innen-Beziehung** 

Die Sichtbarkeit des Elternzugangs wurde vermutlich hier diskutiert: https://github.com/hitobito/hitobito/issues/1965#issuecomment-1384954644

Alle Profile können Verwalter*in (Eltern) oder Kind (verwaltetes Profil) werden, sofern sie entsprechend eingetragen werden. Ob aber der Eintrag sichtbar ist, ist von den Rollen und Rechten abhängig. Die Rolle «Kind» ist nur von Personen in der gleichen Schar (Ebene) sichtbar, nicht von Personen aus darüber liegenden Ebenen: Damit ist die Verbindung zwischen «Eltern und Kind» auch nur sichtbar, wenn eine Rolle in der gleichen Schar (Ebene) vorhanden ist. (Dies gilt auch für die Rolle "Extern")

Ist eine Verwalter*innen-Beziehung (Eltern-Kind) im Profil eingetragen, erscheint im Profil ohne entsprechende Rolle/Berechtigung auf der Ebene der Status "Kinder (keine)" anstelle von "Kinder Name Kind" (person_people_manageds)

Ansicht ohne Rolle/Berechtigung auf der Ebene:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/d60f7d8d-2c72-4780-a72a-bac24c3c8995)
Ansicht mit Rolle/Berechtigung auf allen Ebenen (als Eltern):
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/2495f678-7778-4707-b562-2240e6c229b9)
Ansicht mit teilweise fehlenden Rolle/Berechtigung auf Ebenen (Florian Lauda hat die Rolle "Kind" in einer anderen Ebene/Schar):
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/d837efd8-62c9-4157-94cc-71aea7eec8c2)



Aus dieser Situation leite ich folgende Herausforderungen ab:

- Der Status «Kind» (person_people_manageds) könnte neben der Namen der Kinder (mit Link zum Profil) und (keine) zusätzlich den Namen der Kinder (ohne Link zum Profil) und (nicht sichtbar) abbilden. Damit wäre wie in Gruppen/Ebenen sofort sichtbar, dass zwar Profile vorhanden sind, aber dies aufgrund fehlender Rollen nicht angezeigt oder nicht verlinkt sind. 
("nicht sichtbar" wäre datenschutzfreundlicher, der Name der Kinder (ohne Link) praktikabler)
- Bei einer Selbstregistrierung können Rollen definiert werden bei denen dieses Profil nur von Personen in dieser Ebene sichtbar ist, nicht von Personen aus darüber liegenden Ebenen (Extern / Kind). Schwieriger wird es erst, wenn Verwalter*innen nach einer Selbstregistrierung eine Anmeldung für ihre Kinder in der Ebene/Gruppe vornehmen.
- Bei einer Event-Anmeldung fehlt ebenfalls die Information zum Vorhandensein allfälliger Verwalter*innen-Beziehung (Eltern-Kind). Dies ist insbesondere herausfordernd, da sowohl Eltern wie auch verwaltete Profile die Rolle "Teilnehmer*in" erhalten, aber ihre "Verantwortung" nicht geprüft und nicht sichtbar ist. (Beispiel: Ein Kind wir an einen Anlass angemeldet, die Informationen zu den Eltern sind für den Event-Veranstalter nicht sichtbar) 




**Bitte folgende Idee prüfen:**

- Der Status «Kind» (person_people_manageds) und «Verwalter*innen» (person_people_managers) zeigt jeweils neben dem Status (keine) oder zusätzlich den Namen der Kinder (mit/ohne Link zum Profil) auch den Status (nicht sichtbar) (Optional die Anzahl) an. (Der Wert "keine" obwohl Daten vorhanden sind, könnte als "Bug" ausgelegt werden)
- Bei einer Event-Anmeldung wird der Status der Verwalter*innen-Beziehung als (statischer) Wert in der Anmeldung sichtbar.  Den Event-Verantwortlichen (Leitung, Lagerleitung, evtl. analog Administrationsangaben) müsste dann mindestens der volle Name sichtbar werden. (Optional erweiterbar mit "Option 2" der Sicht auf Teilnehmendendaten). Das Feature "Verwalter*innen-Status" in Event-Anmeldung könnte im Youth-Wagen auf anklang stossen.


Begründung:

Die [Sicht auf Teilnehmendendaten](https://github.com/hitobito/hitobito_jubla/issues/75#issuecomment-1943303248) erscheint als notwendiges Mittel, damit ein Verein/Gruppe/Ebene mit Verwalter*innen-Beziehung irgendwie umgehen kann. Die erwähnte "Option 2" halten wir ebenfalls als bessere Option. Eigentlich müsste es doch aber genügen die Verwalter*innen-Beziehung "lediglich" sichtbar zu machen, ohne das dafür Rollen auf den Ebenen zugeteilt werden müssten. (Wir sehen ein, dass das vergeben von Rollen oder das erweitern der Berechtigungen über Events/Selbstregistrierung eine komplexes Unterfangen mit möglichen Nebenwirkungen sein könnte)

Falls die Idee "funktioniert" könnten wir die Anforderungen dahingehend "abschwächen", dass keine Rollen für eine Event-Anmeldung vergeben werden müssen. Diese Lösung müsste schneller, einfacher und weniger komplex abzubilden sein.
Die Scharen/Event-Verantwortlichen könnten dann bereits sehr umfangreich ihre Verantwortung wahrnehmen: Sofern es ein Mitglied/Anmeldung/Interessent mit unklaren Verwalter*innen-Beziehung gibt, kann reagiert werden und diese Beziehung "geklärt" werden.


Mockup für ein Profil mit Verwalter*innen-Beziehung für welche dem Betrachter die Rechte fehlen:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/6296df5b-cd97-45c7-b726-bc735441f487)

Mockup für eine Event-Anmeldung in welchem die Informationen der Verwalter*innen-Beziehung als Anmelde-Informationen (wohl statisch) mit der Anmeldung gespeichert werden:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/15e4113a-12f0-41e5-9508-3568d7013982)

**Comment by richardjubla** [comment]
Folgende "Ideen" zu Aufträgen (neue Story/Issue) als Ersatz ausarbeiten:

- [ ] Der Status «Kind» (person_people_manageds) und «Verwalter*innen» (person_people_managers) soll jeweils neben dem Status (keine) oder zusätzlich den Namen der Kinder (mit/ohne Link zum Profil) auch den Status (nicht sichtbar und die Anzahl ) an. Umsetzung: Youth-Wagon
- [ ] Bei einer Event-Anmeldung soll der Status der Verwalterinnen-Beziehung als (statischer) Wert in der Anmeldung sichtbar werden. Den Event-Verantwortlichen (Leitung, Lagerleitung, evtl. analog Administrationsangaben) müsste dann den Wert von Status «Kind» (person_people_manageds) und «Verwalter*innen» (person_people_managers) sehen können. Umsetzung: Youth-Wagon
- [ ] Das Formular für die Selbstregistrierung global im jubla-Wagon anpassen. 


Begründung: Die formulierten Ideen sind "gut". Wir können die Story so verfolgen, ohne das Rechtesystem öffnen oder anpassen zu müssen. Die Scharen/Vereine erhalten die Informationen die sie benötigen um eine Registrierung/Event-Anmeldung weiterverfolgen zu können.

**Comment by ThomasEllenberger** [comment]
@nchiapol & @simfeld könnt ihr hier evtl für die Cevi und PBS noch ein kurzes Statement abgeben ob die beiden ersten Punkte von Richi ok wären wenn wir die im Youth Wagon umsetzen?

**Comment by nchiapol** [comment]
@ThomasEllenberger Sorry, das ticket ist zu umfangreich - ich verstehe nicht worum es bei den beiden Punkten geht. Könnt ihr da Mockups der angepassten Ansichten machen?

**Comment by richardjubla** [comment]
> @ThomasEllenberger Sorry, das ticket ist zu umfangreich - ich verstehe nicht worum es bei den beiden Punkten geht. Könnt ihr da Mockups der angepassten Ansichten machen?

@nchiapol ich mache einzelne Issues und werde nochmals konkret anfragen. Es geht um die Themen für den Youth-Wagon in https://github.com/hitobito/hitobito_jubla/issues/75#issuecomment-1946314072

**Comment by richardjubla** [comment]
Diese Story/Issue behält ihre Gültikeit, wird aber in den einzelnen Teilbereichen weitergeführt: 

- https://github.com/hitobito/hitobito_jubla/issues/77
- https://github.com/hitobito/hitobito_jubla/issues/78 
- https://github.com/hitobito/hitobito_jubla/issues/79

**Comment by simfeld** [comment]
> könnt ihr hier evtl für die Cevi und PBS noch ein kurzes Statement abgeben ob die beiden ersten Punkte von Richi ok wären wenn wir die im Youth Wagon umsetzen?

@ThomasEllenberger ich bestätige mal, dass wir dies gesehen haben - leider konnte sich aber noch niemand im Detail damit auseinandersetzen. Bis wann ist eine Rückmeldung für euch hilfreich?
