### ISSUE TITLE
EVENT: Sichtbarkeit/Darstellung der Verwalter*innen-Beziehung

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#77]
Dieses Feature folgt auf #75 und nimmt Bezug auf https://github.com/hitobito/hitobito_jubla/issues/75#issuecomment-1944083248 

Als Mensch der ein Profil aufrufen kann, möchte ich den Status der Verwalter*innen-Beziehung jederzeit überprüfen können um zu sehen, ob das Profil verwaltet wird (Verwalter*innen hat) oder es Kinder verwaltet.
So kann ich zweifelsfrei herausfinden ob es Verwalter*innen-Beziehung(en) gibt und gegebenenfalls darauf reagieren wenn ich solche Profile/Mitglieder verwalte. (Habe ich ein Profil/Mitglied in meiner Ebene/Gruppe/Verein welches verwaltet wird, will ich zum Beispiel den Verwalter*in ebenfalls in meiner Mitgliederverwaltung aufnehmen. Dafür müsste ich das Vorhanden dieser Beziehung immer vermuten, abfragen oder eben nachschauen können)

**Neu soll der Status «Kind» (person_people_manageds) und «Verwalter*innen» (person_people_managers) jeweils zwingend neben dem Status (keine) oder zusätzlich den Namen der Kinder (mit/ohne Link zum Profil) auch den Status (nicht sichtbar und die Anzahl) anzeigen. Der Wert "keine" wird nicht mehr angezeigt, obwohl Daten (Verbindungen) vorhanden sind.**

Umsetzung im Youth-Wagon (oder Jubla-Wagon).

# Akzeptanzkriterien:

- Verein (Schar/Gruppe/Ebene) hat die Verantwortung und Einsicht über die Verwalter*innen-Beziehung aller Profile in ihre eigene Schar/Gruppe/Ebene. 
- Die Implementierung stellt eine reale Zeitersparnis und Mehrwert für den Verein, da er die Verwalter*innen-Beziehung nicht mehr vermuten oder explizit überprüfen muss.

Defintion of Done

- Alle Akzeptanzkriterien wurden erfüllt oder eine alternative gefunden
- Die Implementierung wurde getestet und als fehlerfrei bestätigt.
- Die Dokumentation/Tests wurde(n) aktualisiert.

# Mockup

Mockup für ein Profil mit Verwalter*innen-Beziehung für welche dem Betrachter die Rechte fehlen:
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/6296df5b-cd97-45c7-b726-bc735441f487)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
@nchiapol: Umsetzung im Youth Wagon für euch in Ordnung?

**Comment by nchiapol** [comment]
@ThomasEllenberger Grundsätzlich schon - allerdings habe ich keine Situation gefunden, in der ich zwar das Profil sehen kann, die Verwaltungsbeziehungen aber nicht sichtbar wären. 

Selbst bei den Details der Kursanmeldung scheinen bei uns immer die Namen (einfach ohne Link) sichtbar.

![screenshot_2024-02-21_124934](https://github.com/hitobito/hitobito_jubla/assets/1123483/b9a04c2d-800c-4d74-8b82-3de852552fa7)

**Comment by ThomasEllenberger** [comment]
@nchiapol Stand heute kann man die Verwaltungs- und Verwaltetenbeziehungen nur sehen, wenn man diese auch ausserhalb des jeweiligen Kontexts sehen kann. Wenn du dies also mit einem Administrator auf dem Dachverband ausprobierst, wirst du immer alle Beziehungen sehen können, weil du die Personen auch sonnst sehen kannst.

Das Verhalten tritt nur ein, wenn du sonnst keine Berechtigung hast die Personen zu sehen.
Z.B. du hast nur Rechte in einer Ortsgruppe und jemand von einer anderen Ortsgruppe meldet sich an deinen Anlass an. Da du ausserhalb von diesem Anlass keine Berechtigung die durch diese Person verwalteten Personen zu sehen, wirst du diese also nicht sehen.

Dieses Ticket soll dies noch nicht ändern, soll einem aber klar machen, dass Beziehungen vorhanden sind welche man selbst nicht sehen kann.

**Comment by nchiapol** [comment]
Danke für die Klärung.  Ich habe natürlich nicht als Admin getestet ;-) Möglicherweise haben wir aber in unserem Wagon hier die Rechte erweitert, so dass das Problem in weniger Fällen auftritt:

*) Ein TN kann andere TN in seiner Gruppe sehen. Dort war auch die Verwalterbeziehung sichtbar.
*) Der Kursleiter eines Regionskurses kann die Details seiner TN sehen und bearbeiten. Auch dort sind die Verwaltungsbeziehungen sichtbar.
*) Eine Anlass-Teilnahme gibt den Event-Verantwortlichen das Recht die Kontaktdaten der Person zu bearbeiten. (Selbst wenn sie das Profil sonst nicht sieht. Screenshots unten sind vom Coach einer Ortsgruppe auf die Anmeldung eines TNs einer anderen Ortsgruppe - sonst sind keine Rollen vorhanden.)

![screenshot_2024-02-21_132253](https://github.com/hitobito/hitobito_jubla/assets/1123483/4937c47a-6877-43d9-ac9d-04bce8

![screenshot_2024-02-21_132412](https://github.com/hitobito/hitobito_jubla/assets/1123483/f9f43d7c-cb5c-4580-8afd-471398e3b25a)
f8fd12)

Allenfalls wäre auch diese Lösung, dass eine Anmeldung das Bearbeiten der Kontaktdaten erlaubt, eine Option für die Jubla. Die würde gar keine Anpassung im Code erfordern und möglicherweise diverse weitere Prozesse vereinfachen - und unsere Konfigurationen näher zusammenbringen ;-) (Habe leider gerade nicht herausgefunden, wo das in unserem Wagon konfiguriert ist.)

**Comment by richardjubla** [comment]
> @ThomasEllenberger Grundsätzlich schon - allerdings habe ich keine Situation gefunden, in der ich zwar das Profil sehen kann, die Verwaltungsbeziehungen aber nicht sichtbar wären.
> 
> Selbst bei den Details der Kursanmeldung scheinen bei uns immer die Namen (einfach ohne Link) sichtbar.
> 
>

Beispiel:
https://cevi.puzzle.ch/groups/466/people/3414
https://cevi.puzzle.ch/groups/455/events/1224/participations/128102 
Profil mit der Rolle "Spender/in" (Diese Rolle ist nur von Personen in dieser Ebene sichtbar, nicht von Personen aus darüber liegenden Ebenen.)
https://cevi.puzzle.ch/groups/466/people/3414/history


Die Rolle(n) von Samuel Kustr und die Verwalter-Beziehung ist nur innerhalb der Ebene sichtbar. 
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/f5921549-a652-4093-a761-dc49151eb632)
Ansicht mit Aktive Rollen: Cevi Schweiz / Administrator/-in -> die Verwalter-Beziehung von Samuel Kustr (Mutter Louis Test) ist nicht sichtbar.

Konkret bedeutet dies, dass sowohl die Rolle wie auch die Verwalter-Beziehung bei Kursen (Events) oder bei Veranstaltungen in der zum Beispiel die Eltern (aus Ortsgruppe 1) ein Kind in der Ortsgruppe 2 anmelden, nicht sichtbar sind.  


> @ThomasEllenberger  
Wenn du dies also mit einem Administrator auf dem Dachverband ausprobierst, wirst du immer alle Beziehungen sehen können, weil du die Personen auch sonnst sehen kannst.

Diese Aussage stimmt eben nicht (mehr?): Sowohl im Jubla-Wagon wie auch im Cevi-Wagon werden die Beziehungen mit einem Administrator nicht angezeigt, welche nur von Personen in dieser Ebene sichtbar sind. Dazu muss der Administrator ein Profil imitieren oder sich die Rolle in der Gruppe/Ebene selber geben. 

Unklar ist für mich noch was passiert, wenn die Rolle "verloren" geht wie zum Beispiel hier: https://github.com/hitobito/hitobito_jubla/issues/53

**Comment by richardjubla** [comment]
Ich gehe davon aus, dass mit der "neuen" Darstellung der Verwalter*innen und Kinder im Profil immer sichergestellt ist, dass sichtbar ist, wenn ein Profil verwaltet wird oder selbst ein Profil verwaltet. Die Anforderung dieser Story wäre demnach erfüllt. Wer Profil-Informationen lesen kann, kann demzufolge auch den Verwalter*innen-Status einsehen.

**Comment by richardjubla** [comment]
> Was dadurch nicht abgedeckt ist, ist die Sichtbarkeit von Verwaltern oder Kindern, wenn man nicht das Profil betrachtet.
> Beispielsweise bei einer Anmeldung an einen Anlass kann es weiterhin sein, dass ein Kind von einem Verwalter angemeldet wurde und der Verwalter von den Leitpersonen nicht sichtbar ist.

Korrekt, die Issues #78 und #79 sind weiterhin unserem Weg, um dies zu erreichen. Aus meiner Sicht könnte dieses Issue auch bereits geschlossen werden.

**Comment by richardjubla** [comment]
Ticket schliessen, folgetickets bestehen.
